### ISSUE TITLE
It would be nice in the setNode() method to be able to hide

### ISSUE THREAD

**Issue by ldash** [RGLab/flowWorkspace#100]
only the nodes that are terminal leaves in the current view - that way we would never have disconnected separate trees for the gating hierarchy plotting.

Or specify the functionality that when setting a non-terminal node in the current view to hidden, all of its children are automatically also set to hidden.

Similarly, not to create disconnected components, seems like setting a node to visible should only be allowed for nodes, which are immediately adjacent to the terminal nodes in the current view.

Or alternatively specify the functionality that when setting a node visible, which is not adjacent to a terminal node in the current view, then set visible all of the intermediate nodes between the specified node to set visible and its first already visible parent.

I forget why @mikejiang you mentioned topological ordering in this case, since setNode() manipulates just a single population node at a time...

Any other ideas about this?

**Comment by mikejiang** [comment]
We don't want to necessarily hide the children nodes automatically when a parent node is hidden.  There is a good use case in `lyoplate` project.  One center has the extra `singlet` gate that is absent from all the   other centers. We chose to hide that gate to standardize the gating tree across centers.
