### ISSUE TITLE
insertGate

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#153]
Sometime we need to insert a dummy gate to the GatingSet to make its structure the same as others. To do that, we simply construct a dummy gate that includes all the events

``` r
gate_coordinates <- list(c(-Inf, Inf), c(-Inf, Inf))
 names(gate_coordinates) <- c("FSC-A", "SSC-A")#this center does not have `SSC-H'
 singlet.gate <- rectangleGate(gate_coordinates, filterId = "singlets")
```

then specify the location of the insertion (i.e. `parent` and `children`)

``` r
gs_new <- insertGate(gs
                      , gate = singlet.gate
                      , parent = "/MNC"
                      , children = "/MNC/not dead")
```

Once the `dummy` node is added, we will copy the rest gates to the new tree.

**Comment by malisas** [comment]
The `insertGate` function is discussed here for inserting dummy gates. Is it also safe to use for non-dummy gates? I want to insert a gate right before my CD3 gate to remove artifacts.

**Comment by mikejiang** [comment]
It is now deprecated by  the new API `moveNode`, which is more generic and efficient. 
For the example above, basically, you can do it by adding the gate and then move the target to this gate
```r
add(gh, singlet.gate, parent = "/MNC", name = "singlets")
moveNode(gh, "/MNC/not dead", "singlets")
```
At the moment, it supports `GatingHierarchy`,I haven't implement the overloaded method for `GatingSet`,but it is trivial to iterate it by `lapply`
See its usage here https://github.com/RGLab/flowWorkspace/blob/trunk/tests/testthat/test-moveNode.R

**Comment by malisas** [comment]
Cool, thanks. It looks like this will let me move node `A` and automatically move nodes `A_child_1` and `A_child_2` with it, which is what I need.
