### ISSUE TITLE
drop the dependancy on Boost.Regex

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#160]
Currently we have shipped the `regex` module along with `boost`. 
In order to remove it from the package, we need to wait until `bioc` to upgrade `gcc` from the current `4.6.3` to  `4.9` (which has the full implementation of  `regex`)

**Comment by mikejiang** [comment]
`Boost Graph` was added to `BH` lately and `CRAN-devel-debian` is already using `gcc 4.9.1`. 
Once `bioc-devel` upgrades its `gcc`, we could consider to remove entire bundled `Boost` to reduce the size of source package and its shared library.

**Comment by mikejiang** [comment]
Looking at the `gcc version` for [`windows`](http://cran.r-project.org/web/checks/check_flavors.html), which is still `4.6.3`, It means we need to use `Boost.regex`  on `win` for at least another 3 to 4 years. 

However since `bundled boost` is just for `linux` and `std::regex` and `boost::regex` have compatible APIs, we could simply do the  `OS-specific` header reference  to either `<boost/regex.hpp>` or `<regex>`  by passing a preprossesor flag `-DWIN` to `Makevar.win`.

**Comment by oneillkza** [comment]
@mikejiang  It's worth noting that the package is currently failing to build on Bioconductor, due to some error related to not finding boost regex symbols.

**Comment by mikejiang** [comment]
@oneillkza , see the fix mentioned here https://support.bioconductor.org/p/89667/#89686

I am still debating with myself about whether to remove the `boost regex` source code to resolve this version discrepancy issue once for all so that I don't need tackle this problem everytime `BH` upgrade its `boost` header.

By doing so, the package should build with `bioconductor` without problem since they upgraded `gcc` to `5.4.0`  about 6 months ago. But I still receives the compiling failures from users due to their older `gcc` (<=4.6).  It seems to me that most `HPC` environments are usually reluctant to upgrade their  `gcc`. Therefore dropping bundled `regex` and relying on `gcc` (>=4.9.1) will definitely break things. 
So I would keep doing this temporary fix for a littler longer.

**Comment by oneillkza** [comment]
Yeah a lot of HPC environments (and clinical environments) run CentOS, and upgrading gcc/glibc/etc is a huge pain on that.

**Comment by mikejiang** [comment]
@gfinak , `boost string algorithm` and `boost tokenizer` (both header-only) are now used for the string manipulation instead of `boost_regex`. So we are good for old c++ compiler.

**Comment by oneillkza** [comment]
Yay!
