### ISSUE TITLE
.getPopChnlMapping

### ISSUE THREAD

**Issue by gfinak** [RGLab/flowWorkspace#168]
In `.getPopChnlMapping` the following loop, there is a problem with the logic doing the exact match if `matchCount>1`. 
`matchCount >1` if `this_marker` matches multiple entries in `pop_marker_list`. But `this_marker` is in a loop and the other direction is not tested (i.e. that multiple entries in `all_markers` match an entry in `pop_marker_list`. This leads to mismatches, e.g. when "IL2" in `pop_marker_list` matches "IL2" and "IL21" in `all_markers`. It will return the wrong mapping depending on the order they appear in the `flowFrame`

A fix would be to always to an exact match if `matchCount>0` within the `sapply` loop on `all_markers`.

I will push the change.

```
  is_matched <- sapply(all_markers,function(this_marker){
      this_matched <- sapply(pop_marker_list, function(i)grepl(pattern = i, x = this_marker, fixed=TRUE))
      matchCount <- length(which(this_matched))

    if(matchCount > 0){
      #if(matchCount > 1)
      #{
        # always do an exact match, since all_markers is in an sapply loop
            this_matched <- sapply(pop_marker_list, function(i)match(i, this_marker))
            this_matched <- !is.na(this_matched)
            matchCount <- length(which(this_matched))
        if(matchCount > 1)
          stop(this_marker, " is matched with more than one populations")
      #}
....

}

```

**Comment by mikejiang** [comment]
given this `node` vs `marker` mapping
```r
> map
$`cd4/ifng`
[1] "ifn"

$`cd4/il2`
[1] "il"

$`cd4/tnfa`
[1] "tnf"
```
`getSingleCellExpression` would fail due to the `case sensitive` matching by default
```r
> getSingleCellExpression(gslist[1], nodes, map = map)
.Error in FUN(X[[1L]], ...) : Marker not found: il2
```
It now can succeed by explicitly turning on the `ignore.case` flag, 
```r
>  getSingleCellExpression(gslist[1], nodes,  map = map, ignore.case = T)
           IFN       IL      TNF
 [1,]    0.000    0.000 2947.805
 [2,] 1981.043    0.000 2352.476
 [3,]    0.000    0.000 2013.412
 [4,]    0.000    0.000 2165.409
 [5,]    0.000    0.000 1613.065
 [6,]    0.000 3072.803 3016.527
 [7,]    0.000    0.000 1831.573
 [8,]    0.000 3057.045    0.000
 [9,]    0.000    0.000 1587.135
[10,]    0.000 2132.817 2564.000
[11,]    0.000 1762.973 2325.768
```
