### ISSUE TITLE
Implement export of Gating Sets to GatingML files

### ISSUE THREAD

**Issue by gfinak** [RGLab/flowWorkspace#170]
We are getting increased requests for this feature, specifically internally from Steve, and externally from at least two other groups. 
I think we can justify putting some effort into this. 
Phu had expressed interest in developing this further, as had @jfrelinger .
Could you guys coordinate and put together a prototype?

**Comment by gfinak** [comment]
@ptvan  since you've been working on this, I'm assigning you officially.

**Comment by peterch405** [comment]
Any progress on this?

**Comment by mikejiang** [comment]
We have an implementation [here](https://github.com/RGLab/flowIncubator/blob/master/R/GatingSet2GatingML.R#L16-L21).  It is currently tailored for `Cytobank` but can be extended for `flowJo` eventually.

**Comment by mikejiang** [comment]
Moved to RGLab/CytoML#1
