### ISSUE TITLE
flowWorkspace - index of population

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowWorkspace#174]
I am using flowWorkspace_3.12.04. The doc of getIndices and getGate indicate that the y parameter could be an index (integer I guess), but it seems that it is currently not implemented.
Regards,
Samuel

**Comment by mikejiang** [comment]
`numeric index` is deprecated in favor of `character` name of the population(i.e. full or partial gating path). I will update the doc.
Thanks for pointing it out!

**Comment by SamGG** [comment]
Nice!
