### ISSUE TITLE
fix the infinite corners of polygon gate

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#175]
`openCyto::quadGate.tmix` was introduced to address the issue in `DC` panel where two populations need to be separated with `diagonal cut` and thus the `polygon` has to be used instead of the regular `rectangle` . e.g.
![image](https://cloud.githubusercontent.com/assets/1385649/6193248/31086a04-b36e-11e4-97d3-3e9a0824cc30.png)

This requires some corners of polygon to be far enough in order to cover the events at boundaries region. However we can't assign `Inf` to the `coordinates` because the ordinary `polygon` is a `closed circuit` by definition. And `flowViz` won't render the `open-ended` polygonGate appropriately.

Therefore an extreme finite value (`.Machine$double.xmax`) is currently used in `quadGate.tmix`.
However `pb` archive stores `gate coordinates` as `single float` (which is more efficient and reasonable since flow data is stored as `float` in both `raw FCS` and `hdf`), such value overflows and becomes `Inf` during the `serialization`.

The simple fix is to restore `Inf` to `finite` value for `polygonGate`.  Since the issue is rooted in `flowWorkspace`, would it be more appropriate to do it in `flowWorkspace::getGate` call instead of in `flowViz`. @gfinak ?

**Comment by ldash** [comment]
So what solution / aproach was taken?
