### ISSUE TITLE
Unable to pass additional argument to  read.flowSet when parsing flowjo workspace version 3.16.8

### ISSUE THREAD

**Issue by JauntyJJS** [RGLab/flowWorkspace#188]
Hi,

I was trying to parse a workspace that involves fcs files with double delimiters.

wsfile="C:\\Users\\selvaje1\\Desktop\\20151106_SPPL2ACD14CD74_infectedHumanPBMCAssayDMSOcutoff.wsp.xml"
ws<-openWorkspace(wsfile)
G<-parseWorkspace(ws,name=1,path="C:\\Users\\selvaje1\\Desktop\\FCSData",isNcdf=FALSE)

which gives the following error

Error: Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!

However, adding the additional flag emptyValue=FALSE gives the same error

G<-parseWorkspace(ws,name=1,path="C:\\Users\\selvaje1\\Desktop\\FCSData",isNcdf=FALSE,emptyValue=FALSE)

Error: Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!
In addition: Warning message:
closing unused connection 3 (C:\Users\selvaje1\Desktop\FCSData/A01 MBR046-25uM.fcs) 

However, the above code works in an older version of the same package (version 3.14.9)

I think there is some bug in passing these arguments to read.flowSet or to read.ncdfFlowset for this new version.

Could this be checked ?

Regards,
Jeremy

**Comment by SamGG** [comment]
Hi,
Greg & Mike will answer better than I, but IMHO the error came from reading FCS rather than reading the workspace. What is happening if you do a setwd call first to the FCS dir "C:\Users\selvaje1\Desktop\FCSData" and remove this path from the parseWorkspace command?
Please, do provide the version of your flowCore package.
Best

**Comment by mikejiang** [comment]
It has to do with the new feature introduced by #180 .
I've pushed the fix to `3.16.8`.

**Comment by mikejiang** [comment]
@JauntyJJS , let me know if it works since I don't have such use case to test with.

**Comment by SamGG** [comment]
Hope it will suffice, but if not, do `readFCS("C:/Users/selvaje1/Desktop/FCSData/A01 MBR046-25uM.fcs")` to get a diagnosis.
Best.

**Comment by JauntyJJS** [comment]
Hi,

I have tired it and I realised that the emptyvalue =FALSE options only goes to the arguments for the read.FCSheader. 

Hence the program is now able to read the header without any issue but gives the same error when it tries to read the data using read.flowSet

What I did was to further modify the code to ensure that emptyvalue =FALSE goes to read.flowSet and not just read.FCSheader. 

In the flowJoWorkspace-Methods.R

In the .preprocessor function below the setMethod("parseWorkspace"), line 172
I include the argument emptyvalue =TRUE as default,
and added in line 231 function .parse.pData and line241 function .parseWorkspace "emptyValue=emptyValue"

In .parse.pData, it has read.FCSheader which is already fixed and changed.

In .parseWorkspace, line495, I include  emptyvalue =TRUE  as default
and at line 513 .addGatingHierarchies must have  "emptyValue=emptyValue" because 
this function uses read.flowSet.

.addGatingHierarches can be found in GatingSet-Methods.R line 475,
I include  emptyvalue =TRUE  as default
and at line 503 added read.flowSet(samples[["file"]], emptyValue=emptyValue,...)

That way, using that, the program is able to read the FCS files with double delimiters without any issue using flowset.

However, I am not sure for using the ncdFlowSet case. (I have not tried it yet)
Though it is able to read the fcs files now.

I have encountered another error 
Error in as.list.default(X) :
  no method for coercing this S4 class to a vector

The source of this error is from line 555 of the flowJoWorkspace-Methods.R in the .parseWorkspace, function.

gslist <- suppressMessages(.groupByTree(gs))

I do not understand the purpose of this function of if it has any effects on gs.
This is because in the end, gs is returned and not gslist.

This function .groupByTree is found in merge-GatingSet.R line 12.

Error come from
node_seq <-unlist(lapply(x,function(this_gs){
            this_gh <- this_gs[[1]]
            this_nodes <- getNodes(this_gh, path = "auto")
            #sort it alphabetically
            this_nodes <- sort(this_nodes)
            paste0(this_nodes, collapse = "|")
          }))


May I ask for clarification on the function groupByTree and are they meant to deal with flowSet, ncdfflowSet or both,

Thank you.

Regards,
Jeremy

**Comment by mikejiang** [comment]
These changes are unnecessary if you are using `flowSet` as the backend. `emptyValue` should be able to make it to `read.flowSet` call through `...`.  Is it possible to share your example workspace and FCS file for the troubleshooting?

**Comment by SamGG** [comment]
@JauntyJJS The beginning of your answer is not clear to me.

> I have tired it and I realised that the emptyvalue =FALSE options only goes to the arguments for the read.FCSheader.

Did you try to read one of the FCS files with readFCS function, and did you get no error? Did the call to readFCS need `emptyValue=TRUE` in order to return no error? If `emptyValue` must be set, could copy and paste the header and text parts of the FCS file using an hexadecimal editor (http://www.hexedit.com/ for example)?

**Comment by mikejiang** [comment]
@JauntyJJS , I've verified that `flowSet` version should work as it is. If you want to try `ncdfFlowSet` (i.e. set `isNcdf = TRUE`), you will need to pull the latest flowWorkspace `3.16.10` (I just pushed the fix to BioC)

**Comment by JauntyJJS** [comment]
Hi,

With the updated code, I have verified that the function to parseWorkspace works for isNcdf=FALSE and TRUE for FCS data with double delimiters.

G<-parseWorkspace(ws,name=1,path="C:\Users\selvaje1\Desktop\FCSStuff",isNcdf=FALSE,emptyValue=FALSE)

G<-parseWorkspace(ws,name=1,path="C:\Users\selvaje1\Desktop\FCSStuff",isNcdf=TRUE,emptyValue=FALSE)

Thank you all for your help.

I tried to share the folder containing the workspace and fcs files but github complains that the size is over 10MB. (It comes from a 96 well plate).

Wonder if there is any alternate method to share the workspace and fcs files

Regards,
Jeremy

**Comment by mikejiang** [comment]
@JauntyJJS , I've already created one use case with double-delimiter, so never mind.
Regarding to the question about `groupByTree`, it is simply a sanity check on the consistency of the `gating hierarchy structure` across samples. Because `flowJo` workspace occationally allows the gating tree of some individual samples to be different from the others, which violates the presumption of `GatingSet` class. So we will check it and throw the warning whenever that happens so that users would take actions to fix the source of problem.
