### ISSUE TITLE
Unable to plot gates with attached dataset due to inverse function error

### ISSUE THREAD

**Issue by JauntyJJS** [RGLab/flowWorkspace#189]
[Small.zip](https://github.com/RGLab/flowWorkspace/files/76930/Small.zip)

Hi,

I was trying to plot the gates using the attached workspace and corresponding fcs files. (Small.zip)

library(flowWorkspace)
wsfile="C:\\Users\\selvaje1\\Desktop\\FlowCytoStuff\\Small\\Small.xml"
ws<-openWorkspace(wsfile)
G<-parseWorkspace(ws,name=1,path="C:\\Users\\selvaje1\\Desktop\\FlowCytoStuff\\Small",isNcdf=TRUE,emptyValue=FALSE)

gh<-G[[1]]
nodelist<-getNodes(gh, path = 1)
node<-nodelist[4]
g<-getGate(gh,node)
plotGate(gh,node)
Error: inverse function not defined!

Printing g gives the following
Rectangular gate 'CD14+' with dimensions:
  Comp-FL4-H: (0.590021913541868,0.840021913541868)
  FSC-A: (31622.9780068531,31623.0747810467)

May I know if what can be done fix the inverse function issue ?

Thank you.

Regards,
Jeremy

**Comment by mikejiang** [comment]
Displaying the axis label in `raw scale` by inverse transforming the data range was originally written for `bi-exponential` or `fasinh` (which are most used scaling methods in flowJo).  
I've just added the support for `log` transform in `3.16.11` 

Meanwhile,m If it is not crucial, you can explicitly turn it off by
```r
plotGate(gh, node, raw.scale = FALSE)
```

**Comment by SamGG** [comment]
In an aside - I think it's clear for you, Jeremy, but I would like remind it to other readers - log transform is not defined for zero and negative values. So, for classical cytometers, many compensated values may become undefined and ignored.
