### ISSUE TITLE
add getter and setter methods of 'colnames' and 'markernames' for 'GatingSet'

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#192]
Namely `colnames` , `colnames<-`, `markernames`, `markernames<-` to be operated directly on `GatingSet` or `GatingSetList` objects.

**Comment by mikejiang** [comment]
@gfinak, these two pairs of methods are now propagated to all flow objects. (namely `flowFrame`, `flowSet/ncdfFlowSet`,`ncdfFlowList`, `GatingSet` and `GatingSetList`).

**Comment by gfinak** [comment]
Thanks Mike!
