### ISSUE TITLE
(Feature request) Apply logicle transformation to gatingSet

### ISSUE THREAD

**Issue by O-T** [RGLab/flowWorkspace#193]
I originally posted this on the bioconductor support list: https://support.bioconductor.org/p/77376/

ggcyto supports the axis_x/y_inverse_trans scale, which leaves the data in transformed space, but displays axis labels in an untransformed fashion, which is closer to "reality".
However, ggcyto depends on the transformation being stored in the gatingSet directly, which is currently only possible for flowJoTrans.
I use estimateLogicle() for my workflow and so far have transformed the data before instantiating a gatingSet. I would love and use logicle transformations stored directly in the gatingSet, should this feature become available.  Furthermore, this would allow storage of one more analysis step in direct vicinity of the data. Ideally, the method would be able to handle transformLists, so that multiple channels could be transformed simultaneously.

**Comment by SamGG** [comment]
Mike, if you implement this, could you generalize it to afford asinh and others already standard flowCore transformations? It would be very nice.
Best.

**Comment by mikejiang** [comment]
To be more general, we can support arbitrary `transformation` by using S3 object generated through `scales::trans_new`, which encapsulates everything we need:
* transformation function
* inverse function
* breaks function

**Comment by mikejiang** [comment]
`Transformation` now can be attached and applied to `GatingSet` (and later to be used to inverse transform the axis label for plotting). See [example](https://github.com/RGLab/flowWorkspace/blob/trunk/man/transform.Rd#L33-L40).

And `GatingSet` can use any user-defined `transformation`  as long as its `inverse` is also provided. See **Build the gating hierarchy from scratch** section of the [vignette](https://github.com/RGLab/flowWorkspace/blob/trunk/vignettes/flowWorkspace-Introduction.Rmd) for examples.
