### ISSUE TITLE
xml parsing error

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#194]
Here is the original error report:

On 02/02/2016 11:58 AM, Liu, Hongye wrote:
> Dear Greg,
>
> I am writing to consult you on how to incorporate flowJo workspace that contains CyTOF data.
> I tried to use the flowWorkspace to open a flowJO output of xml that has info of 2 CyTOF experiments and 
> met error on namespaces relating to transforms. Here are some lines of error output. 
>
>
> Namespace prefix transforms for length on fasinh is not defined
>
> Namespace prefix transforms for maxRange on fasinh is not defined
>
> Namespace prefix transforms for T on fasinh is not defined
>
> Namespace prefix transforms for A on fasinh is not defined
>
> Namespace prefix transforms for M on fasinh is not defined
>
> Namespace prefix transforms on fasinh is not defined
>
> Namespace prefix data-type for name on parameter is not defined
>
> Namespace prefix data-type on parameter is not defined
>
> Namespace prefix transforms for length on fasinh is not defined
>
> Namespace prefix transforms for maxRange on fasinh is not defined
>
> Namespace prefix transforms for T on fasinh is not defined
>
> Namespace prefix transforms for A on fasinh is not defined
>
> Namespace prefix transforms for M on fasinh is not defined
>
> Namespace prefix transforms on fasinh is not defined
>
> Namespace prefix data-type for name on parameter is not defined
>
> Namespace prefix data-type on parameter is not defined
> …
>
> Do you think whether it’s something minor that 
> can be fixed without too much coding? You advices will be greatly appreciated. 
> Thank you very much in advance!
>
>
> Best,
>
> Hongye

**Comment by mikejiang** [comment]
These are the `issues` reported by `libxml2` library, which are not treated as errors by `flowWorkspace`. Because `flowJo` does not always output 100% valid standard xml, we decided to ignore the xml errors that are usually not related to `gates` and thus not critical for parsing.

However this time the missing parts are all necessary for `gate` object,
```xml
xmlns:gating="http://www.isac-net.org/std/Gating-ML/v2.0/gating"  
xmlns:transforms="http://www.isac-net.org/std/Gating-ML/v2.0/transformations"  
xmlns:data-type="http://www.isac-net.org/std/Gating-ML/v2.0/datatypes"
```
 thus it did fail eventually 
```r
...
namespace error : Namespace prefix data-type on fcs-dimension is not defined
                                                                             ^
Error: *: unknown transformation type! transforms:linear
```

Without the proper `Namespace definition` for `transforms`, the `Xpath` function `local-name()` returns the entire string `transforms:linear` instead of `linear`, so it does not match the valid `transformation type`.

I am not sure if it is worth to change to parsing code to accommodate such `xml`. The easy fix on user side would be adding these `namespace` as attributes back to root node (i.e. `<Workspace>` node)

e.g.
```xml
<Workspace version="20.0"  flowJoVersion="10.0.7"  xmlns:gating="http://www.isac-net.org/std/Gating-ML/v2.0/gating"  xmlns:transforms="http://www.isac-net.org/std/Gating-ML/v2.0/transformations"  xmlns:data-type="http://www.isac-net.org/std/Gating-ML/v2.0/datatypes" >
```

**Comment by gfinak** [comment]
Can we provide a warning / error message with specific instructions to the user on how to fix this issue?

**Comment by mikejiang** [comment]
Basically we need to capture and parse the error information from `libxml2` and it would be hard to accurately determine what kind of issues they really are.

**Comment by mikejiang** [comment]
It is the first time I've seen this. If we do see it a lot, then I can consider using `name()` instead of `local-name()` to always get full string and manually strip the `prefix`. For now I would be reluctant to do so since we don't know if `:` is also legal for the actual node name in `flowJo`.

**Comment by mikejiang** [comment]
There is an argument `additional.keys` with default value set to `$TOT`, which is used to combine the `fcs filename` with `total number of events` recorded in `FCS keyword` as a unique identifier to make sure the correct file is loaded. The details are described [here](https://github.com/RGLab/flowWorkspace/issues/171)

So there is no problem with `xxx1_01_yyy1.fcs_351619` showing up in error message (maybe we can rephrase the message to avoid the confusion). `xxx1_01_yyy1.fcs` is the actual file name that is looked up from file system.

What this error actually means that either `xxx1_01_yyy1.fcs` can not be found in the `path` you provided or the file exist but the `count` recorded in `fcs` does not matched up to the one in `xml`.
So the first thing you want to try is to check and change (if necessary) the `path` argument.

**Comment by agartland** [comment]
Hi Mike and Greg,
I'm just trying to load a cytof gating file for the first time, but I am getting similar errors (about 1200 of these):

```
Namespace prefix gating for id on Gate is not defined
Namespace prefix gating on RectangleGate is not defined
Namespace prefix gating for min on dimension is not defined
Namespace prefix gating for max on dimension is not defined
Namespace prefix gating on dimension is not defined
```

I can see that they are coming from `libxml` too. Looks like all the `:` are being interpreted as namespace prefixes even though they aren't. After replacing all `:` with `_` I can get libxml to parse the file (actually I still had to wrap the whole thing in a `<root>` tag to address the `libxml` error `Extra content at the end of the document`). But now its no longer readable by `flowWorkspace`.
Any ideas how to work around this? I can attach the XML file if that helps.Thanks

**Comment by mikejiang** [comment]
No, you should not modify gates. `gating:` is indeed the namespace prefix.  See `1.6` of [GatingML](http://flowcyt.sourceforge.net/gating/latest.pdf). You should add the missing `namespace` definition back to the root node (see the example above).

**Comment by agartland** [comment]
Thanks @mikejiang, adding the namespace definitions to the root node worked like you said.
