### ISSUE TITLE
Applying flowWorkspace transform_list to another raw fcs data with the same channel

### ISSUE THREAD

**Issue by JauntyJJS** [RGLab/flowWorkspace#196]
Hi,

I was trying to extract the transformation function from flowjo workspace and apply them to other raw fcs files with the same channel in R.

What I did was as follows but it ended out in an error.

#Extract transformation
transform_list = getTransformations(GT[[1]])

#Read raw file
ncfs  <- read.ncdfFlowSet("A01 KAB344-25uM.fcs")
compMat <- getCompensationMatrices(GT[[1]])
ncfs_comp <- compensate(ncfs, compMat)
ncfs_trans <- transform(ncfs_comp, transform_list)

copying data slice:A01 KAB344-25uM.fcs
write A01 KAB344-25uM.fcs to empty cdf slot...
Error in .local(`_data`, ...) : 
   !Please make sure the unnamed argument is a valid 'transformList' object!

Is there an alternate way to apply the transformation settings from a Flowjo workspace to an independent raw fcs data A01 KAB344-25uM.fcs ?
Attached is the GT object and fcs file required

[GT.zip](https://github.com/RGLab/flowWorkspace/files/133892/GT.zip)

Thank you.

**Comment by mikejiang** [comment]
`transformList` is deprecated by `transformerList` in the latest development branch.  I would encourage you to switch to the new workflow of `transforming` a `GatingSet`. See #193 for details. (It also shows you how to construct a `flowJo` transformation object without having to parse a `flowJo workspace`)

**Comment by JauntyJJS** [comment]
I have installed flowWorkspace_3.17.25 and have done the following

#Load workspace without parsing
wsfile="C:\\Users\\selvaje1\\Desktop\\FlowCytoStuff\\hSPPL2ATest2.wsp"
ws<-openWorkspace(wsfile)
GT<-parseWorkspace(ws,execute=FALSE,isNcdf=TRUE,ignore.text.offset=TRUE,emptyValue=FALSE)

#Get compensation matirx
compMat <- getCompensationMatrices(GT[[1]])

#Get raw fcs file
ncfs  <- read.ncdfFlowSet("C:\\Users\\selvaje1\\Desktop\\FlowCytoStuff\\20160121_145000_20160120_SPPL2a_hPBMCAssay\\A01 KAB344-25uM.fcs")
ncfs <- GatingSet(ncfs)
ncfs_comp <- compensate(ncfs, compMat)

For the transformation, I obtained them by typing

T <- getTransformations(GT[[1]])
IT <- getTransformations(GT[[1]], inverse = TRUE)
trans.func = T[1]$` Comp-FL1-A`
inv.func = IT[1]$` Comp-FL1-A`

They are 
function (x) 
{
    sapply(x, function(i) ifelse(i > 0, log10((i)/max_val)/decade + 
        offset, min_val))
}

function (x, min_val = 0, max_val = 262143, decade = curTrans$decade, 
    offset = curTrans$offset) 
{
    10^((x - offset) * decade) * max_val
}

respectively.

Next, I have created the transform list given in 
trans.obj <- trans_new("myTransform", trans.func, inv.func)
chnls <- colnames(ncfs_comp)[c(3:6,9:12)]
transList <- transformerList(chnls, trans.obj)
ncfs_comp <- transform(ncfs_comp, transList)

My questions are as follows
For transList <- transformerList(Group1, trans.obj), if I have another group of channel that uses a different transformation, I must create another tranlist right i.e transList2 <- transformerList(Group2, trans.obj2) right ?

Next is that I observe that in 
trans.func = T[1]$` Comp-FL1-A`
inv.func = IT[1]$` Comp-FL1-A`

There is also a T[1]$` FL1-A` and IT[1]$` FL1-A` , what is the difference ? Does it imply that I can apply transformation on channel FL1-A without compensation on the fcs data to get the same result?

Finally, as I observed in my functions, there is no input for T[1]$` Comp-FL1-A` 's max_val, decade , min_value and offset. All of my other channel have the same function but I believe that max_val, decade , min_value and offset may be different. Hence for to apply a transformation of FL2-A for example that uses the same function, do I need to create a new trans.obj or continue to use T[1]$` Comp-FL1-A` ?

Thank you for the clarification

**Comment by JauntyJJS** [comment]
After reading some stuff in Flowjo, I realized that Comp-{Some Channel Name} is created when the data has been compensated and can be viewed as a new "channel". So my guess is that T[1]$Comp-FL1-A comes from the transformation of the channel "Comp-FL1-A" when viewed in Flowjo.

This seems to imply that there is a possibility that the gating can be done where the channel name is "Comp-{Some Channel Name}" in Flowjo though it may not be originally available in the FCS file.

Here is an example 

Rectangular gate 'CD14+' with dimensions:
Comp-FL4-H: (0.590021913541868,0.840021913541868)
FSC-A: (31622.9780068531,31623.0747810467)


Given another raw FCS file which has channel FL4-H and FSC-A with the same compensation matrix, I understand from https://github.com/RGLab/flowWorkspace/blob/trunk/vignettes/flowWorkspace-Introduction.Rmd  that it is possible to obtain the compensation matrix form the flow Workspace and apply it to the raw data. 

Correct me if I am wrong but I believe gs <- compensate(gs, comp) will change the values in the channel "FL4-H" instead of creating a new channel called "Comp-FL4-H" and leave the values in the channel "FL4-H alone

My question is if this were to be the case, then is it still possible to add such a gate

Rectangular gate 'CD14+' with dimensions:
Comp-FL4-H: (0.590021913541868,0.840021913541868)
FSC-A: (31622.9780068531,31623.0747810467)

which could be obtained from the flowjo workspace to a generic raw FCS data which uses the same channels and compensation matrix ?

**Comment by mikejiang** [comment]
If you need to add a static gate, you want to make sure its dimensions are exactly the same as the flow data associated with your `GatingSet`. So you have to modify `CD14+` gate before adding it.

Also you can tell `geTransformation` to return `transfomer` object directly by setting `only.function = FALSE` instead of manually constructing it. See `?geTransformation`

**Comment by JauntyJJS** [comment]
Hi, I have tried  

trans.obj <- getTransformations(GT[[1]],only.function=FALSE)
chnls <- colnames(ncfs)[c(3:6,9:12)]
transList <- transformerList(chnls, trans.obj)
ncfs <- GatingSet(ncfs)
ncfs <- transform(ncfs, transList)

and it works.

Can I clarify that the transform function in flowWorkspace is different from the transform function in flowCore ?

**Comment by mikejiang** [comment]
The same `transform` generic function but dispatches to different `S4` methods. So the answer is : yes, they are different.

**Comment by JauntyJJS** [comment]
I have a few more question to ask.
Is it possible for transformerList to contain more than one trans.obj for a different group of channels?

trans.obj1 <- trans_new("Transform1", trans.func1, inv.func1)  #For channel "FSC-A" 
trans.obj2 <- trans_new("Transform2", trans.func2, inv.func2) #For channel "SSC-A"

transList <- transformerList(???)
ncfs_comp <- transform(ncfs_comp, transList)

Next question I would like to ask is does getTransformation able to get transformation formula for Width and Time as well and does transformerList able to apply on Width and Time even though they are not channels ?

**Comment by mikejiang** [comment]
Yes,  you can pass a list of different `transformers` to `transformerList` , e.g.
```r
> library(scales)
> trans.obj <- logicle_trans(n = 5, equal.space = FALSE, w = 0.5, t = 262144, m = 4.5, a = 0)
> trans.obj2 <- asinhtGml2_trans()
> transformerList(c("FL1-H", "FL2-H"), list(trans.obj, trans.obj2))
$`FL1-H`
Transformer:  logicle 

$`FL2-H`
Transformer:  asinhtGml2 

attr(,"class")
[1] "transformerList" "list"
```
Not sure I understand your second question.

**Comment by JauntyJJS** [comment]
I was referring to the columns from the raw data from it is read using flowCore . The columns are usually channels like FSC-H and, SSC-H and so on. There are also columns called "Width" and "Time". If I am not mistaken Time usually go through a linear transformation in Flowjo. "Time" is also in the data(GvHD) as well

When I typed getTransformation on  a Gating Set with data parsed in flowWorkspace. They will give the transform formulas for each channel like FSC-H and SSC-H but not for "Time"

Looking at the transformed summary data,  
GT@data@frames[[fcs_file_name]]@parameters@data

I saw that the Time indeed has been transformed with a range of 455, minvalue of 154 and max value of 609. The raw data for Time should be a minvalue of 0 to a high number (like 1023)

However, getTransformation does not show this Time Transformation at all. Hence I suspect that getTransformation also give formula for columns that related to channels and may not give anything for arbitrary column names in the FCS file. I could be wrong on that,

Also I also realized that transform(GT, transList) does not update the range of the flowFrame data in GT@data@frames[[fcs_file_name]]@parameters@data. The values are still the same as the raw fcs data though the minValue and maxValue have changed due to the transformation.

**Comment by JauntyJJS** [comment]
Can I ask another question as well ?

For ncfs_comp <- compensate(ncfs, compMat), where ncfs is a Gating Set whose fcs data loaded from read.ncdfFlowSet,
is it possible to edit the columns names of the channels in the fcs data that got compensated ?

I know from if the Gating set comes from fcs is loaded from flowSet instead I can change the columns name in

Gating_set@frames[[fcs_file_name]]@expr
and
Gating_set@frames[[fcs_file_name]]@parameters@data$name

to for example FSC-A to Comp-FCS-A just like in flowjo.

I wonder if a similar thing could be done for read.ncdfFlowSet where exprs is empty data ?

**Comment by mikejiang** [comment]
Generally speaking, the usage of  `@` at user level is discouraged. Try to find an API to achieve your goal (if API not existed,  then request it).
So to change column names, simply call `colnames<-` method .e.g.
```r
colnames(gs) <- newCols
```
