### ISSUE TITLE
finding fcs-files

### ISSUE THREAD

**Issue by clawrius** [RGLab/flowWorkspace#205]
Hi and thanks for a great package! 

I had a hard time to track down what was more of an unusual circumstance rather than a bug. Suddenly, flowWorkspace would complain that my FCS-files were not valid. I had recently parsed them during the same session, and I am confident neither FlowJo or flowWorkspace does any write on the FCS-files. I tried resaving and moving the files around to force flowjo to rewrite the xml in hope that it had ill formatted attributes of file names or something a like. I finally found out that the parsed files form flowWorkspace included a plot of a gating tree I had done interactively. Somehow, the filename had been appended with "6438.fcs_7879.tiff", where the first part was a valid filename (checked in flowjo xml file) and the other part random for all I know. The error was thus in trying to parse this tiff file. 

This is somewhat a minor problem, but quite hard to track down. I guess an easy solve would be to force ".fcs$". As I understand it now, the pattern "^name_from_xml.fcs" is matched with system filenames but is negligent to anything after the pattern in the filename. Another way to deal with it might be to throw an error if more than one file matches as it currently is?

Thought I'd share if others experience the same problem as the message is from flowCore and not much help can be found by googling.

I'd be glad to help, 
Best regards
Love Tätting
Linköping University Sweden

**Comment by mikejiang** [comment]
Either your FCS files were tampered by yourself accidentally or you copied the wrong files.
One thing is clear:  `tiff` file is not FCS but an image file .

**Comment by clawrius** [comment]
Hi!

Thanks for soon reply. I think I was a bit obscure on the exact behaviour that puzzled me. 

My wsp-file was in directory A and FCS-files in directory in A/B. I then made a plot that accidentally got the name of the fcs-file prepended to the image name and was put in A/C/D. Thus, there was a file named xyz.fcs_abc.tiff in directory D. 

The error occurred the next time I tried to parse the files. Unbeknownst of xyz.fcs_abc.tiff in a subdirectory, it was collected as an FCS file in parseWorkspace due to "xyz.fcs" being a valid filename (i.e. collected as an $FIL-attribute in previous parse). 

When the absolute filenames were sent to read.FCSheader, the offset read didn't correspond to a valid FCS file (as it was a tiff file) and the error "Not valid FCS file header..." was reported. 

The error was thus my fault, and should be easily replicated by touching and naming a file to a valid fcs-filename and appending anything to it in a location below the wsp-file. I just thought other might find themselves in the same situation and wanted to give a hands on recommendation on how to remedy it. 

Best Regards/
Love Tätting

**Comment by mikejiang** [comment]
We can't restrict the range of file searching by only looking at the filename ended with `.fcs` because there are situations where filenames were modified and the header was used to match up the samples. 
To aid the trouble shooting for the end user, I updated the `FCS parser` (`flowCore` package) so that it also prints the file name that causes the failure e.g.
```r
> gs <- parseWorkspace(ws, path = dataDir, name = 4)
Error in FUN(X[[i]], ...) : 
  Error in if (!version %in% c("FCS2.0", "FCS3.0", "FCS3.1")) stop("This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file") : 
  argument is of length zero
~/flowWorkspaceData/extdata/CytoTrol_CytoTrol_1.fcs.tiff
```
@clawrius , thank you for reporting this, which helped us to improve the usability of our tools.
