### ISSUE TITLE
GatingSetList() fails when using samples argument due to unexpected behavior of validObject()

### ISSUE THREAD

**Issue by paulobrecht** [RGLab/flowWorkspace#209]
I have a flow dataset on which I can run `gsl <- GatingSetList(G)` without issues. However, when I try to run `gsl <- GatingSetList(G, samples=toKeep)`, I get this error:

```
Error in validObject(x) : 
  invalid class “GatingSetList” object: 'samples' slot is not consisitent with sample names from GatingSets!
```

The GatingSetList() function fails due to something within validObject(). However, running `test <- ncdfFlowList(G, samples=toKeep)` works just fine. And when I redefine GatingSetList() such that it is unchanged except removal of the validObject() test, the samples argument works and the resulting object seems to in fact be valid

**Comment by mikejiang** [comment]
`samples` argument is used for sample `ordering`  , Not for `subsetting`. I will clarify that in the documentation as well.
If `ncdfFlowList` constructor does not throw the error for this, then the same validity check needs to be added to it
