### ISSUE TITLE
Error in readFCSheader :location of FCS files

### ISSUE THREAD

**Issue by akhst7** [RGLab/flowWorkspace#215]
After selecting a group I need to analyze by parseWorkspace, I get the following error message;

> Selection: 14
Error in FUN(X[[i]], ...) : Error in readFCSheader(con) : This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file /Volumes/Documents/Users/akihoji/Library/Mobile Documents/com~apple~CloudDocs/Flow/CMVTet_Dex/TSne/LD-ACUTE_LD-A1_C01_003.fcs_DownsampleDP.Pop_tSNE__Movie_Event_20000_Perp_30_MIter_5_Eta_200_Iter_1000_Theta_0.5/LD-ACUTE_LD-A1_C01_003.fcs_DownsampleDP.Pop_tSNE__Movie_Event_20000_Perp_30_MIter_5_Eta_200_Iter_1000_Theta_0.5.html

 

CMVTet_Dex/ is a directly created by Flowjo after using its plugins but evidently,  parseWorkspace thinks that is where corresponding fcs files are.  Is there an way to manually indicate the location of FCS in parseWorkspace  ? 

Thanks

**Comment by mikejiang** [comment]
see `path` section of `?parseWorkspace`, I am also going to push a patch so that only filenames ended with `.fcs` will be searched.
