### ISSUE TITLE
"Correct" way to check which marker names and channel names are paired?

### ISSUE THREAD

**Issue by malisas** [RGLab/flowWorkspace#217]
Given a `GatingSet`, I want to check which marker names and channel names are paired (i.e. without having to re-assign using `markernames(gs) <- myNamedCharacterVector`).

Is there a way to obtain a named vector like the following?
```r
> namedMarkers
       <QDot 655-A>          <PE Cy5-A>        <PE Tx RD-A>         <APC Cy7-A> <PerCP Cy55 Blue-A>    <Pacific Blue-A>  <PE Green laser-A> 
             "CD14"             "CD154"               "CD3"               "CD4"               "CD8"              "IFNg"               "IL2" 
            <APC-A>       <Alexa 680-A>          <PE Cy7-A>            <FITC-A>         <Am Cyan-A> 
              "IL4"             "IL17a"              "IL22"              "TNFa"              "AViD" 
```
* * * * * * *
I realized that I cannot always rely on `markernames(gs)` and `colnames(gs)`. For instance, in the following example, the channel name `"PE Cy55-A"` in index 12 does not match up to anything in the `markernames(gs)` vector.
```r
> colnames(gs)
 [1] "Time"                "FSC-A"               "FSC-H"               "SSC-A"               "<Pacific Blue-A>"    "<Am Cyan-A>"        
 [7] "<QDot 655-A>"        "<PE Green laser-A>"  "<PE Tx RD-A>"        "<PE Cy5-A>"          "PE Cy55-A"           "<PE Cy7-A>"         
[13] "<APC-A>"             "<Alexa 680-A>"       "<APC Cy7-A>"         "<FITC-A>"            "<PerCP Cy55 Blue-A>"
> markernames(gs)
 [1] "IFNg"  "AViD"  "CD14"  "IL2"   "CD3"   "CD154" "IL22"  "IL4"   "IL17a" "CD4"   "TNFa"  "CD8" 
```
I also noticed the following method of obtaining marker and channel names per `flowFrame`, but not all the channel and marker names appear:
```r
> parameters(getData(gs, j = colnames(gs))[[1]])[[1]]
[1] "Time"                "FSC-A"               "FSC-H"               "SSC-A"               "<Pacific Blue-A>"    "<Am Cyan-A>"        
 [7] "<QDot 655-A>"        "<PE Green laser-A>"  "<PE Tx RD-A>"        "<PE Cy5-A>"          "PE Cy55-A"           "<PE Cy7-A>"         
[13] "<APC-A>"             "<Alexa 680-A>"       "<APC Cy7-A>"         "<FITC-A>"            "<PerCP Cy55 Blue-A>"
> parameters(getData(gs, j = colnames(gs))[[1]])[[2]]
   <NA>    <NA>    <NA>    <NA>    $P5S    $P6S    $P7S    $P8S    $P9S   $P10S    <NA>   $P12S   $P13S   $P14S   $P15S   $P16S   $P17S 
     NA      NA      NA      NA  "IFNg"  "AViD"  "CD14"   "IL2"   "CD3" "CD154"      NA  "IL22"   "IL4" "IL17a"   "CD4"  "TNFa"   "CD8" 
```

Thanks!

**Comment by ptvan** [comment]
If I understand your question correctly, the answer is no, there is no automatic way to know how to pair flourescence channels (eg. "Cy5") with the antibody/marker used (eg. "IL2") in a gatingSet/flowSet. This is because both these pieces of information are filled out by the experimenter, and sometimes people simply do not fill them out, or make a mistake, etc. The flow API allows you to fill in the marker if known (via ```markerNames()```) but which marker corresponds to which channel is an experimental question, not a software one, since it depends on the experiment(er)s involved. Using the example above, there is nothing preventing a lab technician from using "Cy7" for "IL2" vs. "Cy5"

**Comment by mikejiang** [comment]
To get the mapping, retrieve the data.frame from underling `flowFrame`
```r
> pData(parameters(getData(gs[[1]])))[,1:2]
       name   desc
$P1   FSC-A   <NA>
$P4   SSC-A   <NA>
$P9    Live B515-A
$P13   CCR7 G560-A
$P10    CD4 B710-A
$P14 CD45RA G780-A
$P11    CD3 V450-A
$P12  HLADR V545-A
$P7    CD38 R660-A
$P8     CD8 R780-A
```

So, `colnames` gives you `name` column, and `markernames` gives you `desc` column (by filtering out those `NA` values, which is why the length is usually shorter than `colnames` vector)

**Comment by ptvan** [comment]
@malisas: What I said above still applies using Mike's code snippet. For example, I have had datasets where there are two channels named `CD8`, or `desc` is not filled out, etc. So if you're lucky, you get something like the data.frame above with one-to-one correspondence. If not, then you have to ask the people who gave you the data. Never Assume(TM).

**Comment by malisas** [comment]
I see. Thank you @ptvan and @mikejiang .
Got it, I am slowly learning to Never Assume(TM)!
Still good to know the `pData(parameters(getData(gs[[1]])))[,1:2]` command, I think it will be useful for sanity checking.
