### ISSUE TITLE
Error when using plotGate

### ISSUE THREAD

**Issue by Jincheng2009** [RGLab/flowWorkspace#218]
I implemented a gating workflow using flowWorkspace, and everything works fine. Great tool ! 
But when I tried to plot the results using `plotGate(gs[[1]])`, I got an error message saying `Error in eval(substitute(expr), envir, enclos) : DAPI- not found!`

My workflow has a gate named `DAPI-|CD3+`, but `plotGate(gs[[1]], "DAPI-|CD3+")` works which gives me the plot of this `DAPI-|CD3+` gating. If I changed the gate name from `DAPI-|CD3+` to `live CD3+`, `plotGate(gs[[1]])` works.

But other gates name like `CD62L-|CCR7+` does not have this problem. I think it may be a regular expression problem?

Thanks

**Comment by mikejiang** [comment]
It is the '|' character in your population name that interferes the `gate merging` process (which happened to use '|' as the string delimiter ). I will push a patch to address this.

**Comment by Jincheng2009** [comment]
Thanks. Could I use space in the gate name for now? like DAPI- CD3+

**Comment by mikejiang** [comment]
Yes, with the patch, you should be able to use any character except '/' which is reserved for the delimiter of gating path.
