### ISSUE TITLE
Is it possible to add the full path of events falling in the particular gate to the data frame in the flowjoworkspace

### ISSUE THREAD

**Issue by akhst7** [RGLab/flowWorkspace#220]
I am wondering if there is a trick to write  the full path (e.g. singlets/live/lymph/CD3/CD4) or alias (CD3CD4) of events  in the particular gate into the new column (e.g. gate ) to the data frame in the  flowjoworkspace object ?

**Comment by gfinak** [comment]
I don't quite understand your question. 
>  the particular gate into the new column (e.g. gate ) to the data frame in the flowjoworkspace object

The above is unclear. What data frame are you talking about? The `flowJoWorkpace` object has no such data frame component. Do you perhaps mean a `GatingSet`, returned by `parseWorkspace`?

Here's my guess at what you might mean: 
If you have a GatingSet, which is returned by `parseWorkspace`, you can extract population statistics using `getPopStats`, that takes an argument, `path`, which is a `character`  vector, and if it's specified as `path="full"`, it will return the full path of each cell population in the `Population`  column in the returned data frame of cell population statistics.
`getPopStats(gatingset,path="full")`

If this doesn't address your question, please clarify, perhaps with some code demonstrating the expected behavior.

**Comment by mikejiang** [comment]
And to get `event` wise matrix , use `exprs(getData(gs[[i]], 'singlets/live/lymph/CD3/CD4'))`, then you can add a column of `full path` to this table. 
This is also based on my guess of your meaning

**Comment by akhst7** [comment]
I am sorry that my question was not clear.  I use the following code to extract transformed and compensated FCS table;
`test<-openWorkspace(file = "~/Desktop/test_tSNE.wsp")
ws<-parseWorkspace(test)
fs<-getData(ws)
ts<-exprs(fs[[1]])`

After downsizing and adding tSNE values, I get this table as follows. 
> > str(ts)
Classes ‘data.table’ and 'data.frame':	20000 obs. of  15 variables:
 $ CD43        : num  159 124 134 121 143 ...
 $ Dex         : num  51.3 52.9 63.6 63.9 60.6 ...
 $ CD28        : num  74.8 107.8 129.2 100.7 83.8 ...
 $ CD45RA      : num  99.7 135.6 85.2 96.2 79.6 ...
 $ CD27        : num  133.7 81.9 173 164.8 151.6 ...
 $ CD269       : num  144.6 98.7 115.1 117.4 95 ...
 $ CD14CD16CD19: num  55.3 60.1 63.1 62.1 59.8 ...
 $ CD57        : num  26.9 22.7 32.2 28.7 29 ...
 $ CD3         : num  145 87.8 154.2 141.4 67 ...
 $ KLRG1       : num  128.3 85.5 183.8 182.3 178.7 ...
 $ CD8         : num  188.8 17.3 189.1 175.4 114.1 ...
 $ CD56        : num  76.8 50.6 78 66.8 156.8 ...
 $ CD38        : num  155 203 156 141 158 ...
 $ tSNE1       : num  -4.55 -5.55 -20.99 -18.74 10.6 ...
 $ tSNE2       : num  -24.21 14.59 -0.36 2.24 19.11 ...
 - attr(*, ".internal.selfref")=<externalptr> 

What I'd like to do now is to add, gating information, either full path or alias to the new column as follows;

>
 $ CD43        : num  159 124 134 121 143 ...
 $ Dex         : num  51.3 52.9 63.6 63.9 60.6 ...
 $ CD28        : num  74.8 107.8 129.2 100.7 83.8 ...
 $ CD45RA      : num  99.7 135.6 85.2 96.2 79.6 ...
 $ CD27        : num  133.7 81.9 173 164.8 151.6 ...
 $ CD269       : num  144.6 98.7 115.1 117.4 95 ...
 $ CD14CD16CD19: num  55.3 60.1 63.1 62.1 59.8 ...
 $ CD57        : num  26.9 22.7 32.2 28.7 29 ...
 $ CD3         : num  145 87.8 154.2 141.4 67 ...
 $ KLRG1       : num  128.3 85.5 183.8 182.3 178.7 ...
 $ CD8         : num  188.8 17.3 189.1 175.4 114.1 ...
 $ CD56        : num  76.8 50.6 78 66.8 156.8 ...
 $ CD38        : num  155 203 156 141 158 ...
 $ tSNE1       : num  -4.55 -5.55 -20.99 -18.74 10.6 ...
 $ tSNE2       : num  -24.21 14.59 -0.36 2.24 19.11 ...
 $Gate          :Factor "Singlets/Live/CD3/CD8", >

This  is what I meant by generating the new column and adding gating information the data.frame. 

I hope this clears  up a bit. 

Thanks.

**Comment by mikejiang** [comment]
Assuming your  `ts` table is still the original size and `Gate` column is divided by the `non-overlapping` gates, you can do this
```r
gate.column <- vector(mode="character", length = nrow(fs[[1]]))
for(gate.name in c("Singlets/Live/CD3/CD4", "Singlets/Live/CD3/CD8"))
{
 bool.ind <- getIndices(gs[[1]], gate.name)
 gate.column[ bool.ind] <- gate.name
}
```

**Comment by gfinak** [comment]
Is this issue resolved? @akhst7 please close it if so.
