### ISSUE TITLE
Clarification on allowed gate types for getSingleCellExpression

### ISSUE THREAD

**Issue by malisas** [RGLab/flowWorkspace#224]
**Short version:**  
What is the definition of a `1d marginal gate`?  
**Long version:**  
The [comments above `getSingleCellExpression`](https://github.com/RGLab/flowWorkspace/blob/0442382718ccfad8e9e97318edaab624dfde2255/R/getSingleCellExpression.R#L148) define the `marginal` parameter as:
> indicates whether to the gate is treaded as 1d marginal gate. Default is TRUE, which means markers are determined either by node name or by 'map' argument explained below. When FALSE, the markers are determined by the gate dimensions and node name and 'map' argument are ignored.

In other words, it seems that when `marginal = TRUE`, only `1d marginal gate`s are allowed.  
Specifically, I have these questions:  
1. What is the definition of a `1d marginal gate`? Which gates are allowed, and which are not? Why would the shape of the gate affect how data is pulled from the tree of indices in each population?
2. I am able to pass in a `polygonGate` when `marginal = TRUE`. Is a `polygonGate` a `1d marginal gate`?
3. If I import gates from a flowJo workspace, will they all be compatible with `getSingleCellExpression` when  `marginal = TRUE`? What about when  `marginal = FALSE` (It [looks like](https://github.com/RGLab/flowWorkspace/blob/0442382718ccfad8e9e97318edaab624dfde2255/R/getSingleCellExpression.R#L216) `booleanFilter` gates are not allowed)?

Example of my `polygonGate`:
```r
> cd3Gate <- getGate(gs, "CD3")$`01-0381_3515326`
> attributes(cd3Gate)
$filterId
[1] "CD3"

$boundaries
      FSC-A <G610-A>
[1,] 190464 2226.714
[2,] 190464 4018.141
[3,]  55296 4018.141
[4,]  55296 2226.714

$parameters
An object of class "parameters"
[[1]]
unitytransform on parameter 'FSC-A'

[[2]]
unitytransform on parameter '<G610-A>'


$class
[1] "polygonGate"
attr(,"package")
[1] "flowCore"
```

**Comment by mikejiang** [comment]
If `marginal == TRUE`,  the `marker` (or 'column') is chosen based on the name of that `gate` (or `node`), e.g. fluorescence intensity of `CD3` will be part of the output in your case (regardless of the dimension of `cd3Gate`). If it is set to `FALSE`, both  `FSC-A` and `<G610-A>` will appear in the output.

**Comment by malisas** [comment]
I see. I think I was confused about 1) marker selection vs 2) cell subset selection.

So the comment about `indicates whether to the gate is treaded as 1d marginal gate` is in regards to the marker names which are imported as columns, right?

The actual subset of events/row indices should not be affected by the type of node, correct? (excluding the boolean gates which seem to be a problem)

**Comment by mikejiang** [comment]
Yes, it was about the marker selection. cell events selection is controlled by gating results (regardless of gate type). 
bool gate is excluded is because there is no dimensions associated with the gate so we can't deduce marker information from the gate when `margin == FALSE`

**Comment by malisas** [comment]
That makes a lot of sense, thanks.
