### ISSUE TITLE
Sample without any gate cannot be detected

### ISSUE THREAD

**Issue by Jincheng2009** [RGLab/flowWorkspace#225]
I tried to extract compensation matrix for all the samples inside a flowjo workspace file using `flowWorkspace`
Some samples are not gated and they cannot be detected by `parseWorkspace` function
Is that possible to allow parsing sample with no gate ?

**Comment by gfinak** [comment]
It is.

```
>?parseWorkspace
...
 • requiregates ‘logical’ Should samples that have no gates
              be included?
```

**Comment by mikejiang** [comment]
If they are not added to the `GatingSet` through `parseWorkspace`, then you will have to use `flowCore::spillover` method to extract `compensation` from each FCS, e.g.

```r
dataDir <- system.file("extdata",package="flowWorkspaceData")
fr <- read.FCS(list.files(dataDir, pattern = "*.fcs",full = TRUE)[1])
spillover(fr)
```

**Comment by Jincheng2009** [comment]
@gfinak @mikejiang Thank you both for the response. I did not notice the option of `requiregates` , this solves my issue. We have samples not compensated well at the beginning, so the compensation matrix inside FCS is not working, so need to compensate in flowjo and then extract them.
