### ISSUE TITLE
attributes(getGate())$boundaries don't match plotGate() gate boundary lines

### ISSUE THREAD

**Issue by malisas** [RGLab/flowWorkspace#226]
I would like to categorize a few hundred cells based on their CD4 and CD8 MFI values after running t-SNE on them. After t-SNE, the cells are no longer part of a GatingSet, so I am manually categorizing the cells by extracting the gate boundaries from their original GatingSet. However, the gate boundary values don't seem to match the boundary lines on the FACSPlot for that gate. For example:

```r
> attributes(getGate(gs["01-0959_3581690"], "CD4")[[1]])
$filterId
[1] "CD4"

$boundaries
        <B710-A> <R780-A>
[1,] -781499.500 3728.059
[2,]    2913.024 3744.035
[3,]    2603.186 1641.891
[4,] -781499.500 1645.436

$parameters
An object of class "parameters"
[[1]]
unitytransform on parameter '<B710-A>'

[[2]]
unitytransform on parameter '<R780-A>'


$class
[1] "polygonGate"
attr(,"package")
[1] "flowCore"
> plotGate(gs["01-0959_3581690"], "CD4")
```
![rplot1](https://user-images.githubusercontent.com/16787492/28728324-10227ce0-737d-11e7-873e-696990f98d30.png)

You can see that on the plot, the R780-A range is from ~950 to ~100,000. But the attributes(getGate()) boundaries are from 1641.891 - 3744.035.

Are the data being transformed in some way? Thanks for your advice.

**Comment by mikejiang** [comment]
the plot displays the axis label in raw scale and gates and data are actually in transformed scale. This is the default visualization effect desired by biologists. You can switch the label to transformed scale and it is more intuitive to do so in `ggcyto`, e.g.
```r
#axis label in transformed scale
p <- ggcyto(gs, aes(CD8, CD4)) + geom_hex() + geom_gate("CD4")
p
```
![image](https://user-images.githubusercontent.com/1385649/28729552-aaa4fdf2-7381-11e7-9560-80a6e42ccd6b.png)

```r
p + axis_x_inverse_trans() #switch label of x axis to raw scale
```
![image](https://user-images.githubusercontent.com/1385649/28729517-8c32c6f6-7381-11e7-8d2f-debd0e34f10d.png)

**Comment by malisas** [comment]
Thanks, that clears things up. I just want to verify that the following steps are valid:

1.  Obtain MFI values for cells using `getSingleCellExpression()`. These values are transformed, correct?
2.  Manually categorize cells using values from Step 1 and the boundaries from `attributes(getGate())$boundaries`, which are transformed values.

**Comment by mikejiang** [comment]
yes, as I said, all the gates and data values are stored as transformed scale in GatingSet
