### ISSUE TITLE
tSNE plot with the selected population

### ISSUE THREAD

**Issue by akhst7** [RGLab/flowWorkspace#228]
Hi, 

I'd like to make a tSNE plot in which clusters in the plot are color coded by particular subsets (see a figure attached).  I do this by  first extracting raw compensated data (flowWorkspace), run tSNE (RtSNE), add tSNE x and y values back to the flow data and then import it into the flowjo to color code the subset of cells to clusters on the tSNE map.  Is there any easier way to do this by perhaps using  flowWorkspace, Rtsne, and  ggplot ? 

Thanks in advance. 

[tSNEsmall.pdf](https://github.com/RGLab/flowWorkspace/files/1299969/tSNEsmall.pdf)

**Comment by gfinak** [comment]
You can do this using the `ggcyto` package. [tsne integation in ggcyto](http://rstudio-pubs-static.s3.amazonaws.com/249045_19875297a3c842cc8f3de75c30f350a7.html)
[ggcyto package](http://www.github.com/RGLab/ggcyto)

**Comment by akhst7** [comment]
Thanks but ggcyto tsne does not appear to be in RG github. 

> install_github("RGLab/ggcyto/tsne")
Downloading GitHub repo RGLab/ggcyto@master
from URL https://api.github.com/repos/RGLab/ggcyto/zipball/master
Installation failed: 404: Not Found

**Comment by gfinak** [comment]
Because if you look carefully, you'll see you should download the "trunk" branch. There is no "master" branch.

**Comment by gfinak** [comment]
And it's not "ggcyto/tnse" it's just "ggcyto"

**Comment by mikejiang** [comment]
`install_github("RGLab/ggcyto", ref = "tsne")`

**Comment by akhst7** [comment]
Ok then you need to change the install code in the web page.

**Comment by SamGG** [comment]
Hi all.
The initial question mentions a "coloring step" that will be done in FlowJo. I think the interactive ability of FJ will allow the experimenter to interact with the tSNE XY plot and to benefit of the information of the original as well, The interesting article (I missed it and only read it in diagonal yet) seems to build subsets of cells from the 'degree of functionality'. This score sounds to be an integer with a few discrete values and eases building subsets. Which alternate approach might be applied with only tSNE coordinates and original channels?
Cheers.

**Comment by gfinak** [comment]
If using a `GatingSet` of data imported from a flowJo workspace, then cell membership into individual gates is available and one can color the cells in tsne space based on that, which is my understanding of the original question.

**Comment by SamGG** [comment]
Thanks for sharing your view. My understanding was different.

**Comment by akhst7** [comment]
Hi Greg,

Could you show me an example script of how to extract the cell membership information from the GatingSet object and color the cells in the tSNE map ?

Thanks.

**Comment by gfinak** [comment]
Here's an example. Not the prettiest, since it's not doable directly through ggcyto.
```

**Comment by akhst7** [comment]
Thanks !!

This should help.
