### ISSUE TITLE
Error in getAttrsNode(self, n, attr) : attrname is needed

### ISSUE THREAD

**Issue by nicbarker** [RGLab/flowWorkspace#232]
Hi,
Thanks for the great work across the opencyto project.
I've just started using the libraries and was able to plot the graph and gates for the sample data. When trying to do the same with some of our own data, I'm getting an error when trying to use `plot(gs[[1]])`:
```
> plot(gs[[1]])
Error in getAttrsNode(self, n, attr) : attrname is needed
> traceback()
8: stop("attrname is needed")
7: getAttrsNode(self, n, attr)
6: nodeData(g, nodeID, attrName)
5: nodeData(g, nodeID, attrName)
4: as.vector(nodeData(g, nodeID, attrName))
3: .getGraph(x[[1]])
2: plot(gs[[1]])
1: plot(gs[[1]])```
```
`gs[[1]]` appears to be a valid `GatingHierarchy`:
```
gs[[1]]
Sample:  st_SS10_Rho_009.fcs_451620 
GatingHierarchy with  75  gates
```
If you could point me in the right direction that would be greatly appreciated, I can also try and provide any additional information that would help.

**Comment by mikejiang** [comment]
What is the output of `getNodes`? I may need the minimum reproducible example from you to troubleshoot .

**Comment by nicbarker** [comment]
Hi Mike,
Thanks for the quick reply. The output of getNodes also looks ok.
```
> getNodes(gs[[1]])
 [1] "root"
 [2] "/FSC-A, Live Dead near IR subset"
 [3] ...
 [75] ...
```
I'll find out from my supervisor the extent to which I can give you data to look at.

For reference, the error at the top of the backtrace is from rgraphviz:
https://github.com/Bioconductor-mirror/Rgraphviz/blob/master/R/attrs.R#L292
