### ISSUE TITLE
Installation failed due to cytolib compilation problem 

### ISSUE THREAD

**Issue by akhst7** [RGLab/flowWorkspace#234]
Cytolib compilation fails at 

> clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.4.2/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o cytolib.so GatingHierarchy.o GatingSet.o GatingSet.pb.o POPINDICES.o calibrationTable.o compensation.o delimitedMessage.o ellipse2points.o flowData.o gate.o global.o nodeProperties.o spline.o transformation.o All my packages loaded Mon Nov 13 12:49:27 2017/Volumes/Documents/Users/akihoji/Library/R/3.x/library/RProtoBufLib/lib/libprotobuf.a -L/usr/local/Cellar/r/3.4.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help
clang-5.0: error: no such file or directory: 'All'
clang-5.0: error: no such file or directory: 'my'
clang-5.0: error: no such file or directory: 'packages'
clang-5.0: error: no such file or directory: 'loaded'
clang-5.0: error: no such file or directory: 'Mon'
clang-5.0: error: no such file or directory: 'Nov'
clang-5.0: error: no such file or directory: '13'
clang-5.0: error: no such file or directory: '12:49:28'
clang-5.0: error: no such file or directory: '2017/Volumes/Documents/Users/akihoji/Library/R/3.x/library/RProtoBufLib/lib/libprotobuf.a'
make: *** [cytolib.so] Error 1

My platform;

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin17.0.0 (64-bit)
Running under: macOS High Sierra 10.13.1

ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

gcc (Homebrew GCC 7.2.0) 7.2.0
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

Thanks.

Aki

**Comment by gfinak** [comment]
Are you installing from `biocLite` or `devtools::install_github` or locally? Have you tried all of these approaches, do they all give the same error?

**Comment by akhst7** [comment]
A git version worked. 

thanks.
