### ISSUE TITLE
Gate coordinates 

### ISSUE THREAD

**Issue by akhst7** [RGLab/flowWorkspace#235]
Any ways to find XY coordinates of rectangular and quadrant gates ?

**Comment by gfinak** [comment]
From what object?

**Comment by akhst7** [comment]
Any objects but is it possible to do this from the GatingSet object ?

**Comment by gfinak** [comment]
Sure, call getGate() on the GatingSet with the name of the node you want to
retrieve. This will give you a Gate obejct that you can inspect. The bounds
are in there in one of the object slots.
