### ISSUE TITLE
Increasing size of nodes of gating tree using plot()

### ISSUE THREAD

**Issue by cjungR** [RGLab/flowWorkspace#240]
Hello,

Is there a way to increase the size of nodes using `plot`? I can increase the font size, but I can't seem to find a way to increase the node size accordingly by height. I can increase dimensions of the plot itself to make the words fit, but it would like to increase the size of the node itself.  The `width` and `height` arguments for `plot` don't seem to change anything. Thanks for your help. 

![image](https://user-images.githubusercontent.com/26584881/36446202-75b34462-1635-11e8-914f-6fcbbd209f58.png)

**Comment by mikejiang** [comment]
I've pushed the fix. You should be able to pass `width` and `height` to `Rgraphviz` now.
Alternatively , you can hide the node boundary by passing `shape = "plaintext"`

**Comment by cjungR** [comment]
That worked! Thank you for your help.
