### ISSUE TITLE
Error Parsing FlowJo Workspace

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#241]
Hi Mike,

I am trying to parse a flowJo workspace but keep getting the following error during gating step:

![image](https://user-images.githubusercontent.com/28646736/36566863-d0058c6e-1878-11e8-94da-d594fa5f1521.png)

How do I go about fixing this?

Thanks,

Dillon

**Comment by mikejiang** [comment]
pass `extend_val = -100` to `parseWorkspace` to see if that helps

**Comment by DillonHammill** [comment]
Thanks this is working now.
