### ISSUE TITLE
parsing channel with special chars

### ISSUE THREAD

**Issue by musikutiv** [RGLab/flowWorkspace#242]
if channel names contain grep-sensitive characters such as brackets (in my case "Indo-1 (violet)-A", the workspace parser will generate a "channels mismatched between compensation and flow data" error

a simple fix would be in GatingSet_Methods.R to replace 

line 506 
markerInd <- unlist(lapply(marker, function(thisMarker)grep(paste0("^", thisMarker , "$"), cnd, ignore.case = channel.ignore.case)))
                  
with
markerInd <- match(marker, cnd)

cheers 
Tobias

**Comment by mikejiang** [comment]
The fix is pushed. Try again.
