### ISSUE TITLE
Error processing Stratedigm .fcs files

### ISSUE THREAD

**Issue by AngusNano** [RGLab/flowWorkspace#249]
Hi,

I have a problem parsing a workspace with .fcs files acquired on our Stratedigm flow cytometer.

parseWorkspace returns the following error.

```
Error in .getSamples(x, wsType, sampNloc = sampNloc) : 
  sample name is not found in 'keyword' node!Please try 'sampleName' node by setting sampNloc = ‘sampleName
```

If I set sampNloc = ‘sampleName’, I get the following error:

```
Error in match.arg(sampNloc, c("keyword", "sampleNode")) : 
  'arg' should be one of “keyword”, “sampleNode”
```

If I set sampNloc = ‘sampleNode’, parseWorkspace starts to work and asks me to chose which files to import, however when I select the sample I always get the error:

```
Error in .addGatingHierarchies(gs, pd, execute, isNcdf, wsType = wsType,  : 
  no sample to be added to GatingSet!
```

I think the problem stems from the .fcs files lacking the $FIL keyword.

Is there a way of parseWorkspace relying on a different keyword?

I tried to work around this issue by manually adding the $FIL keyword to the .fcs files before processing the datafiles in FlowJo using the following code:

      fl <- read.flowSet(path=as.character(inFolder), transformation=FALSE)
      
      num_files = length(fl)
      
      for (x in c(1:num_files)) {
        
        file.fix <- identifier(fl[[x]])
        new.keyword <- list ("$FIL" = file.fix[[1]])
        keyword(fl[[x]]) <- new.keyword
        
      }
      
      outdir=file.path(as.character(inFolder),"fix")
      
      write.flowSet(fl, outdir)

However the data in the .fcs files seem to get transformed in the process, and the data appears off scale in FlowJo.

Any help would be appreciated.

Cheers

Angus

**Comment by mikejiang** [comment]
The parser looks up FCS files either by filename or by `$FIL` keyword, there is currently no other way of finding files. I am pretty sure this is also how flowjo searches for files.
Make sure you set `path` argument properly to the directory that contains your fcs files. `$FIL` is pretty commonly used keyword and I don't know why your FCS doesn't have it (is it typical for Stratedigm?).
But again, if flowJo finds them, we should be able to do so as well.
Feel free to send along the example wsp file and fcs and I can take a further look.

**Comment by AngusNano** [comment]
Hi Mike,

Thanks for getting back to me so quickly.

Yes, FlowJo can find the files. I was using the legacy version of FlowJo (v9) and saving an .xml file, but when I switched to FlowJo X and opened the .wsp file, parseWorkspace runs ok (if I use sampNloc = ‘sampleNode’). However, the resulting data from all the log channels is very small (ranging from about -0.2 to 1). Is there a transform that I need to apply? If I open the same .fcs files using read.FCS, the log channels give the correct values. I have attached the wsp and fcs files if you can have a look.

Cheers

Angus

**Comment by mikejiang** [comment]
You forgot to post the data

**Comment by AngusNano** [comment]
Sorry, I replied to the email and the attachment didn't come through. Here they are:
[Flowjo_test.zip](https://github.com/RGLab/flowWorkspace/files/2055932/Flowjo_test.zip)

**Comment by mikejiang** [comment]
I don't see anything wrong with the parsing. Gate looks fine. counts matched well. The reason you saw the small data range is because it is `log` transformed (as specified in xml)
```r
> library(flowWorkspace)
> ws <- openWorkspace("/loc/no-backup/mike/shared/Flowjo_test/test_workspace.wsp")
> gs <- parseWorkspace(ws, name = 2, sampNloc="sampleNode")
> library(ggcyto)
> autoplot(gs[[1]])
> getPopStats(gs[[1]])
   openCyto.freq  xml.freq openCyto.count xml.count  node
1:     1.0000000 1.0000000          15386     15386  root
2:     0.6761991 0.6753542          10404     10391 Cells
> fs <- getData(gs)
> fs[[1]][,1:10]
flowFrame object '#NFluoSphere #t120mins - 3'
with 15386 cells and 10 observables:
                             name                         desc
$P1                      FSC LogH                     FSC LogH
$P2                      FSC LogA                     FSC LogA
$P3                      FSC LinH                     FSC LinH
$P4                      FSC LinA                     FSC LinA
$P5                      SSC LogH                     SSC LogH
$P6                      SSC LogA                     SSC LogA
$P7                      SSC LinH                     SSC LinH
$P8                      SSC LinA                     SSC LinA
$P9  642nm Alexa700 (710_40) LogH 642nm Alexa700 (710/40) LogH
$P10 642nm Alexa700 (710_40) LogA 642nm Alexa700 (710/40) LogA
            range   minRange   maxRange
$P1  9.999847e-01 -0.2041047 7.9588e-01
$P2  9.999847e-01 -0.2041047 7.9588e-01
$P3  6.553500e+04  0.0000000 6.5535e+04
$P4  6.553500e+04  0.0000000 6.5535e+04
$P5  9.999847e-01 -0.2041047 7.9588e-01
$P6  9.999847e-01 -0.2041047 7.9588e-01
$P7  6.553500e+04  0.0000000 6.5535e+04
$P8  6.553500e+04  0.0000000 6.5535e+04
$P9  9.999847e-01 -0.2041047 7.9588e-01
$P10 9.999847e-01 -0.2041047 7.9588e-01
197 keywords are stored in the 'description' slot
> fs[[1]][,1:5]
flowFrame object '#NFluoSphere #t120mins - 3'
with 15386 cells and 5 observables:
        name     desc        range   minRange   maxRange
$P1 FSC LogH FSC LogH 9.999847e-01 -0.2041047 7.9588e-01
$P2 FSC LogA FSC LogA 9.999847e-01 -0.2041047 7.9588e-01
$P3 FSC LinH FSC LinH 6.553500e+04  0.0000000 6.5535e+04
$P4 FSC LinA FSC LinA 6.553500e+04  0.0000000 6.5535e+04
$P5 SSC LogH SSC LogH 9.999847e-01 -0.2041047 7.9588e-01
```
![image](https://user-images.githubusercontent.com/1385649/40798896-09bcebb6-64c1-11e8-8848-ce4a31ed458f.png)
