### ISSUE TITLE
Cannot install: "#error This file was generated by an older version of protoc which is..."

### ISSUE THREAD

**Issue by micdonato** [RGLab/flowWorkspace#251]
Hello.

I am trying to install flowWorkspace on our lab server, and I am encountering a lot of issues.

Basically, I installed `cytoLib` and `RProtoBuf` from github, so that I have the latest version (with ` devtools::install_github("RGLab/PACKAGE", ref='trunk')`)

When I try to install `flowWorkspace` in the same way, I get the following error:

```
/home/myuser/R/x86_64-pc-linux-gnu-library/3.4/RProtoBufLib/include/GatingSet.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/myuser/R/x86_64-pc-linux-gnu-library/3.4/RProtoBufLib/include/GatingSet.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/myuser/R/x86_64-pc-linux-gnu-library/3.4/RProtoBufLib/include/GatingSet.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
```

I tried to install both the packages from Bioconductor instead, but no luck.

I am on CentOS 7, gcc 4.9.2, R 3.4.1

I am not sure of what I can do at this point.

**Comment by gfinak** [comment]
Your R version is out of date. So is your gcc, horrendously so.
Update your R version, and install from Bioconductor.
