### ISSUE TITLE
Counts from parsed workspace are different than the ones in FlowJo

### ISSUE THREAD

**Issue by micdonato** [RGLab/flowWorkspace#252]
Hello,

I am trying to get data from a FlowJo workspace, and some of the cell counts are consistently different.

I import the file with:

```
library(flowWorkspace)
wsfile = '/PathToFile/myworkspace.wsp'
ws <- openWorkspace(wsfile)
gs <- parseWorkspace(ws, name = 1, cleanup = TRUE)
popstats = getPopStats(gs)
```

All the cell populations are the same, with the exception of one of the subsets (HLADR, CD19 subset). This is the screenshot from FlowJo:
<img width="379" alt="screen shot 2018-07-18 at 5 47 40 pm" src="https://user-images.githubusercontent.com/36861962/42915119-ca801e6a-8ab2-11e8-8e06-218bf1204eb9.png">

And this is the result of `getPopStats(gs)`:

<img width="419" alt="screen shot 2018-07-18 at 17 50 11" src="https://user-images.githubusercontent.com/36861962/42915164-10029648-8ab3-11e8-8cb4-616099dcb149.png">

I don't know how to troubleshoot this. The only warning I get from FlowWorkspace is when I parse the workspace, and I get this:

```
Warning message:
In .parseWorkspace(xmlFileName = file.path(obj@path, obj@file),  :
  GatingSet contains different gating tree structures and must be cleaned before using it!
```

I tried to find out from the documentation how  to "clean" the gating set but to no avail.

As a side note, exporting the same data to CSV shows the rights counts, therefore I am reasonably confident that the issue is not in the export process, but somewhat I am not using FlowWorkspace properly.

Lastly, my `sessionInfo()`:

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.0.dev.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] EpiTOFSlim_0.9.9          knitr_1.20                flowWorkspace_3.28.1     
 [4] ncdfFlow_2.26.0           BH_1.66.0-1               RcppArmadillo_0.8.600.0.0
 [7] flowCore_1.46.1           ggplot2_3.0.0             magrittr_1.5             
[10] data.table_1.11.4        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17        mvtnorm_1.0-8       lattice_0.20-35     corpcor_1.6.9      
 [5] assertthat_0.2.0    digest_0.6.15       mime_0.5            R6_2.2.2           
 [9] plyr_1.8.4          stats4_3.5.1        pcaPP_1.9-73        evaluate_0.10.1    
[13] highr_0.7           pillar_1.2.3        zlibbioc_1.26.0     rlang_0.2.1        
[17] lazyeval_0.2.1      Rgraphviz_2.24.0    hexbin_1.27.2       DT_0.4             
[21] Rtsne_0.13          stringr_1.3.1       htmlwidgets_1.2     munsell_0.5.0      
[25] shiny_1.1.0         httpuv_1.4.4.2      compiler_3.5.1      pkgconfig_2.0.1    
[29] BiocGenerics_0.26.0 IDPmisc_1.1.17      htmltools_0.3.6     tidyselect_0.2.4   
[33] tibble_1.4.2        gridExtra_2.3       matrixStats_0.53.1  XML_3.98-1.11      
[37] later_0.7.3         flowViz_1.44.0      rrcov_1.4-4         dplyr_0.7.6        
[41] withr_2.1.2         MASS_7.3-50         grid_3.5.1          jsonlite_1.5       
[45] xtable_1.8-2        gtable_0.2.0        scales_0.5.0        graph_1.58.0       
[49] KernSmooth_2.23-15  stringi_1.2.3       promises_1.0.1      bindrcpp_0.2.2     
[53] latticeExtra_0.6-28 robustbase_0.93-1   RColorBrewer_1.1-2  tools_3.5.1        
[57] Biobase_2.40.0      glue_1.2.0          DEoptimR_1.0-8      purrr_0.2.5        
[61] crosstalk_1.0.0     yaml_2.1.19         colorspace_1.3-2    cluster_2.0.7-1    
[65] bindr_0.1.1        
```

**Comment by micdonato** [comment]
Thanks for the reply.
I believe I can, but let me check with the PI :)

**Comment by micdonato** [comment]
So, we do have a workspace with FCS file that we can share. It does not need to be private, as all the data is anonymized. 
What is the best way to share it with you?

**Comment by gfinak** [comment]
Email it to Mike Jiang if it fits as an attachment, or post it here if it's okay that it's public.

**Comment by micdonato** [comment]
There is no personal information (besides the username of the tech :) ) , it is ok to post it here.

Thanks!

[FlowTest.zip](https://github.com/RGLab/flowWorkspace/files/2221404/FlowTest.zip)

**Comment by mikejiang** [comment]
I am not able to parse your example wsp file due to the missing of upper boundary of `RectangleGate`. As shown below, only `min` is present, but no `max`. Are you able to reload this wsp into flowJo and properly display this rectangle gate?
```xml
<Population name="NKT cells" annotation="" owningGroup="" expanded="1" sortPriority="10" count="344">
<Graph smoothing="1" backColor="#ffffff" foreColor="#000000" heatMapStatParameter="Bi209Di" type="Contour" fast="1">...</Graph>
<Gate gating:id="ID1568500815">
<gating:RectangleGate eventsInside="1" annoOffsetX="0" annoOffsetY="0" tint="#000000" isTinted="0" lineWeight="Normal" userDefined="1" percentX="0" percentY="0">
<gating:dimension gating:min="94.08080289877704">
<data-type:fcs-dimension data-type:name="Er170Di"/>
</gating:dimension>
<gating:dimension gating:min="53.789515090732024">
<data-type:fcs-dimension data-type:name="Yb172Di"/>
</gating:dimension>
</gating:RectangleGate>
</Gate>
</Population>
```

**Comment by micdonato** [comment]
Hmmm, I saw the tech loading the workspace in FlowJo right before she sent it to me, and there seemed to be no problems in the cell populations. I will try again today and let you know. Basically I need to load the wsp and check the gating for NKT cells, right?

**Comment by mikejiang** [comment]
Yes

**Comment by micdonato** [comment]
So, the wsp file works fine in our FlowJo. What we noticed is that we use quadrant gates instead of rectangle gates for many of our populations (including the NKT cells you mention).

It seems like FlowJo does not export the quadrant gate as such, but it exports as a RectangleGate without upper bounds.

<img width="389" alt="screen shot 2018-07-31 at 3 25 47 pm" src="https://user-images.githubusercontent.com/36861962/43491565-e8258014-94d9-11e8-9e96-09570d36fab0.png">

**Comment by micdonato** [comment]
Thanks!

**Comment by mikejiang** [comment]
Actually when I loaded this wsp file into flowJo, I wasn't even able to display data or gates properly
![image](https://user-images.githubusercontent.com/1385649/43541796-1d0467ea-9580-11e8-803e-9855f0a0b362.png)
Only after I adjusted the transformations for both axis to log scale, can I see the gates
![image](https://user-images.githubusercontent.com/1385649/43541683-d9336a5c-957f-11e8-8d6c-13755fbf98de.png)
And I see the `transformation` recorded in the wsp workspace are mostly linear
![image](https://user-images.githubusercontent.com/1385649/43540783-891313d0-957d-11e8-9ef3-845cfe2f3557.png)
which I think could be something you want to double check.

**Comment by mikejiang** [comment]
Turned out to be the bad linear transformation parameter `maxRange = 0` that messed up the gate coordinates.
![image](https://user-images.githubusercontent.com/1385649/43546983-cf250b88-958e-11e8-9dc6-d9ac1b39b17e.png)
After properly handling this exception, I am able to parse the example workspace correctly.
```r
> getPopStats(gs[[1]])
    openCyto.freq    xml.freq openCyto.count xml.count                         node
 1:   1.000000000 1.000000000          70239     70239                         root
 2:   0.004897564 0.004897564            344       344                    NKT cells
 3:   0.045871951 0.045871951           3222      3222               Q1: CD3- CD56+
 4:   0.974860335 0.974860335           3141      3141            CD14, CD33 subset
 5:   0.987901942 0.987901942           3103      3103                     NK cells
 6:   0.545907544 0.545907544          38344     38344             Q3: CD3+ , CD56-
 7:   0.642369080 0.642369080          24631     24631                 CD4+ T cells
 8:   0.028378872 0.028378872            699       699  Central memory CD4+ T cells
 9:   0.423571922 0.423571922          10433     10433        Effector CD4+ T cells
10:   0.239210751 0.239210751           5892      5892 Effector memory CD4+ T cells
11:   0.308838456 0.308838456           7607      7607           Naive CD4+ T cells
12:   0.009362612 0.009362612            359       359             CD4+CD8+ T cells
13:   0.161459420 0.161459420           6191      6191                 CD8+ T cells
14:   0.004684219 0.004684219             29        29  Central memory CD8+ T cells
15:   0.622839606 0.622839606           3856      3856        Effector CD8+ T cells
16:   0.176385075 0.176385075           1092      1092 Effector memory CD8+ T cells
17:   0.196091100 0.196091100           1214      1214           Naive CD8+ T cells
18:   0.186808888 0.186808888           7163      7163              Q4: CD4- , CD8-
19:   0.403166332 0.403166332          28318     28318             Q4: CD3- , CD56-
20:   0.119146832 0.119146832           3374      3374                      B cells
21:   0.417331732 0.417331732          11818     11818           HLADR, CD19 subset
22:   0.580385852 0.580385852           6859      6859          Classical monocytes
23:   0.002876967 0.002876967             34        34       Intermediate monocytes
24:   0.001861567 0.001861567             22        22       Nonclassical monocytes
25:   0.414875613 0.414875613           4903      4903            Q8: CD14- , CD16-
26:   0.000000000 0.000000000              0         0                         mDCs
27:   0.108912910 0.108912910            534       534                         pDCs
    openCyto.freq    xml.freq openCyto.count xml.count                         node
```
However, the `transformation` is still a little odd for this example wsp and I am not sure if this will fix your problem with the orginal workspace file. (They seemed to me to be somewhat different)
Anyway, pull the latest trunk and let me know.

**Comment by micdonato** [comment]
Thanks Mike, I will try the trunk and let you know. 

As for the transformations, I think in our case most of them (I actually thought that all of them should be) need to be linear transformations, as this is a particular type of data. However, it is worth investigating. 

Thanks again!

**Comment by micdonato** [comment]
So, the tech made me notice that the counts are still not quite correct. In particular, the mDCs show 0, while in FloJo they still show 424 (we re-loaded the workspace). 

As for the transformation issue, they were not concerned (their answer: "Beads channels are irrelevant because they are used to compensate for the detector sensitivity loss (drifting). In fact, the data we give you always pass through a pre-processing algorithm on the CyTOF instrument, which removes the beads"

**Comment by mikejiang** [comment]
Can you provide me with the same workspace that has mDCs?

**Comment by micdonato** [comment]
Hmmm that *is* the same workspace. We loaded it two days ago and we do see mDCs

**Comment by mikejiang** [comment]
I mean the workspace you sent has `mDCs` count = 0 as well in flowJo

**Comment by micdonato** [comment]
Ha. I just downloaded the one that was attached here and re-sent it to the tech, let's see what she observes. 
Thanks again for your help Mike!
