### ISSUE TITLE
installation of flowWorkspace failed

### ISSUE THREAD

**Issue by staedlern** [RGLab/flowWorkspace#254]
Hi,

I tried to install flowWorkspace via 

source("https://bioconductor.org/biocLite.R");
biocLite("flowWorkspace")

Unfortunately installation failed with error message:

** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘flowWorkspace’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/pstore/home/staedlen/R/x86_64-pc-linux-gnu-library/3.4/flowWorkspace/libs/flowWorkspace.so':
  /pstore/home/staedlen/R/x86_64-pc-linux-gnu-library/3.4/flowWorkspace/libs/flowWorkspace.so: undefined symbol: _ZN5boost16re_detail_10660014verify_optionsEjNS_15regex_constants12_match_flagsE
Error: loading failed
Execution halted

It would be great if you could help me!

Thanks a lot,

Nicolas

**Comment by gfinak** [comment]
Start by updating your R version to 3.5.1, which is the current release.

**Comment by gfinak** [comment]
A bit more info: the precompiled binary you're installing for version 3.4 is looking for the boost library, (and for whatever reason can't resolve those symbols on your system). 
The current version of `flowWorkspace` no longer uses boost.

**Comment by staedlern** [comment]
Hi Greg

Thanks a lot. All good now.

Best wishes,

Nicolas
