### ISSUE TITLE
Transformation slot of GatingSet not updating with multiple transformation steps

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#257]
Hi @mikejiang,

It seems that if you use multiple transformation steps on a GatingSet the transformation slot only contains the TransformerList for the last transformation. I think this list should be updated after each transformation so that it contains the entire transformerList for the GatingSet.

```{r}
# gs is a GatingSet
trans <- estimateLogicle(gs[[1]], "PE-A")
gs <- transform(gs, trans)
gs[[1]]@transformation

> $`PE-A`
Transformer:  logicle 

attr(,"class")
[1] "transformerList" "list"   

trans2 <- estimateLogicle(gs[[1]], "Alexa Fluor 488-A")
gs <- transform(gs, trans2)
gs[[1]]@transformation

> $`Alexa Fluor 488-A`
Transformer:  logicle 

attr(,"class")
[1] "transformerList" "list"  

# I think the output should be:
> $`PE-A`
Transformer:  logicle 

$`Alexa Fluor 488-A`
Transformer:  logicle 

attr(,"class")
[1] "transformerList" "list"   
```

Cheers,
Dillon

**Comment by mikejiang** [comment]
You should estimateLogicle (and later transform) all the channels in one call.

**Comment by DillonHammill** [comment]
This is what I would normally do, but if you happen to miss a channel in the initial estimateLogicle call it would be nice if you could just add the transformation for that channel and then extract the entire transformerList from the GatingSet for use next time.

**Comment by mikejiang** [comment]
For the second case, you can estimateLogicle individually on each channel, then merge them into a single `trasnformerList`. 
I am not convinced that transforming the GatingSet incrementally is the common and unavoidable use case we should cover.

**Comment by DillonHammill** [comment]
Ok I will then assume that the GatingSet is either completely un-transformed or all fluorescent channels are transformed.
