### ISSUE TITLE
 '.fix_channel_slash' not found

### ISSUE THREAD

**Issue by mehrnoushmalek** [RGLab/flowWorkspace#260]
Hello Mike & Greg,

I get  the error of : Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.fix_channel_slash' not found when running GatingSet2flowJo() on version 3.29.9.
It seems that in the latest version fix_channel_slash() is not hidden ( doesn't have "." ).

**Comment by mikejiang** [comment]
update `CytoML` with the latest github trunk

**Comment by gfinak** [comment]
In that case, flowWorkspace should have a dependency on that specific version of CytoML that has the function.

**Comment by mehrnoushmalek** [comment]
I updated everything, except that I forgot to update cytoML, and ggcyto.
Now I get the error of : ```
booleanNode(gate, pop, count, env.nodes = env.nodes, param = param,  : 
  isNot flag must be TRUE in 'Not' boolean gate!
```
Could it be related to adding clean cluster?

**Comment by gfinak** [comment]
I'm  a bit lost, can you post a [reprex](https://github.com/tidyverse/reprex)?

**Comment by mikejiang** [comment]
If you need to output to flowJo, then you can't use `logical` vector, instead, add it as `factor` and it will be treated as cluster labels (as Greg showed in his example)

**Comment by mikejiang** [comment]
Here is related issue that may also help you to understand the procedures https://github.com/RGLab/CytoML/issues/45

**Comment by mehrnoushmalek** [comment]
Thanks @gfinak, yes factor works just fine. I had previously changed it to logical to avoid the underscore.
