### ISSUE TITLE
How to make save_gs() save only the subsetted samples?

### ISSUE THREAD

**Issue by malisas** [RGLab/flowWorkspace#263]
I noticed that if I do the following (for example):
```r
gs <- load_gs("gs_path_in") # A GatingSet with 40 samples
gs_mini <- gs[1] # Subset to the first sample
save_gs(gs_mini, "gs_path_out")
```
The size of the `gs_path_in` and `gs_path_out` folders are both the same size, e.g. 22 GB. The netcdf file seems to get fully copied over.

Is there a way to save a subsetted GatingSet to disk so that it only saves/copies the data which is in the subset? I am trying to create a reproducible example and would like to share just a small subset of my data.

Thank you.

**Comment by gfinak** [comment]
We do this deliberately. Writing to the cdf file is time consuming. You can save via:
```
save_gs(gs_mini,"gs_path_out",cdf = "symlink")
```
This will symlink the existing cdf file, and the subset will simply be in the R object.

**Comment by gfinak** [comment]
Oops, I didn't finish reading your comment.. you really do need a smaller cdf file: I believe `clone()` will do what you need.

**Comment by malisas** [comment]
That worked! Thanks.
```
gs_mini_clone <- clone(gs_mini)
save_gs(gs_mini_clone, "gs_path_out")
```
