### ISSUE TITLE
Drop the dependancy on flowViz,latticeExtra,gridExtra,lattice,RBGL

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#267]
Since we are deprecating `plotGate` with `autoplot`, all the visualization should be either taking place in `ggcyto` or re-implemented through `ggplot` (e.g. `plotPopCV`) , so that we can reduce the package dependencies on these legacy tools.

**Comment by jacobpwagner** [comment]
This should be good after 62b8996e3af27283fe01a61adc2587db5654bb6a and 5e14004b505c7a8567f759d8bca35ce8ac5d1f79 (because I forgot to clip out RBGL too)
