### ISSUE TITLE
Modify vignette to reflect the latest changes from cytolib2.0

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#270]
* New data containers
  * `cytoframe`, `cytoset`
* API behavior changes
  * `GatingSet` is purely a `reference` now

**Comment by jacobpwagner** [comment]
Updated vignette in 4d5a03ec302bf5e7d669d230dcfceb674855cafd. I opted to just push it rather than PR, but if you see the need for changes or improvements, let me know.

**Comment by mikejiang** [comment]
This is great, Thanks @jacobpwagner !
