### ISSUE TITLE
standardize R API following some naming convention

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#274]
Need to have a discussion

**Comment by mikejiang** [comment]
```tex
flowWorkspace-deprecated {flowWorkspace}	R Documentation
Deprecated functions in package flowWorkspace.

Description

getNodes –> gs(/gh)_get_nodes

setNode –> gs(/gh)_set_node/gs(/gh)_hide_node/gs(/gh)_unhide_node

getData –> gs(/gh)_get_data

flowData –> gs_flow_data

flowData<- –> gs_flow_data<-

filterObject –> filter_to_list

plotGate –> autoplot

getPopStats –> gs(/gh)_get_popstats

plotPopCV –> gh_plot_popcv

getGate –> gs(/gh)_get_gate

setGate –> gs(/gh)_set_gate

getParent –> gs(/gh)_get_parent

getChildren –> gs(/gh)_get_children

getProp –> gh_get_proportion

getTotal –> gs(/gh)_get_count

getSingleCellExpression –> gs_get_singlecell_expression

getFullNodePath –> gh_get_full_path

openWorkspace –> open_workspace

isGated –> gh_is_gated

isNegated –> gh_is_negated

isHidden –> gh_is_hidden

openWorkspace –> open_workspace

getTransformations –> gh_get_transformations

getCompensationMatrices –> gh_get_compensations

isNcdf –> gs_is_h5

clone –> gs_clone

recompute –> gs_recompute

getLoglevel –> get_log_level

setLoglevel –> set_log_level

rbind2 –> gslist_to_gs

add –> gs(/gh)_add_gate

Rm –> gs(/gh)_remove_gate

copyNode –> gh_copy_gate

openWorkspace –> open_workspace

flowJo.flog –> flowjo_flog

flowJoTrans –> flowjo_biexp

flowJo.fasinh –> flowjo_fasinh

flowJo.fsinh –> flowjo_fsinh

flowJo_fasinh_trans –> flowjo_fasinh_trans

getDescendants –> gh_get_descendants

getStats –> gs(/gh)_get_stats

groupByTree –> gs_group_by_tree

groupByChannels –> gs_group_by_channels

checkRedundantNodes –> gs_check_redundant_nodes

dropRedundantNodes –> gs_drop_redundant_nodes

dropRedundantChannels –> gs_drop_redundant_channels

updateChannels –> gs_update_channels

moveNode –> gh_move_node

updateIndices –> gh_set_pop_indices

getMergedStats –> gs_get_merged_stats

set.count.xml –> gh_set_xml_count

```

**Comment by jacobpwagner** [comment]
A first pass at the plan for the `openCyto` API overhaul. After discussion with @mikejiang, some of the class exports can be removed as they are only really being used internally. Hence all of the `<remove export>` recommended actions. The `gs(gt?)` are because we aren't 100% sure if we should prefix these `gs_` or `gt_`, not because they are different methods.
```
openCyto-deprecated {openCyto}    R Documentation
Deprecated functions and classes in package openCyto

Description

Classes:

gatingTemplate -> gating_template
Most of the following are exported but probably don't need to be:
boolMethod
gtMethod
gtPopulation
polyFunctions
ppMethod

Functions:

Some of these exports can be removed if the class exports above are removed:
.between_interval -> <remove export>
add_pop -> gs_add_pop
remove_pop -> gs_remove_pop
add_pop_init -> gs_add_pop_init
cytokine -> ff_cytokine
flowClust.1d -> ff_flowclust_1d
flowClust.2d -> ff_flowclust_2d
gate_flowClust_1d -> ff_gate_flowclust_1d
gate_flowClust_2d -> ff_gate_flowclust_2d
gate_mindensity -> ff_gate_mindensity
gate_mindensity2 -> ff_gate_mindensity2
mindensity2 -> <deprecate alias>
gate_quad_sequential -> ff_gate_quad_sequential
quadGate.seq -> <deprecate alias>
gate_quad_tmix -> ff_gate_quad_tmix
prior_flowClust -> fs_prior_flowclust
quadGate.tmix -> <deprecate alias>
gate_quantile -> ff_gate_quantile
quantileGate -> <deprecate alias>
gate_tail -> ff_gate_tail
tautString -> tautstring
tautStringGate -> ff_gate_tautstring <add export>
gating -> gs(gt?)_gating
gatingTemplate -> gating_template
toggle.helperGates -> gs(gt?))_toggle_helpergates
get.helperGates -> gs(gt?)_get_helpergates
delete.helperGates -> gs(gt?)_delete_helpergates
listgtMethods -> gt_list_methods
registerGatingFunction -> <remove export (already defunct)>
registerPlugins -> register_plugins
templateGen -> gh_template_gen
add -> <remove export>
getChildren -> gt_get_children
getGate -> gt_get_gate
getNodes -> gt_get_nodes
getParent -> gt_get_parent
names -> <remove export>
parameters -> <remove export>
```
Also, if we would prefer `fr` to `ff` for `flowFrame`, that's fine too. I just felt `ff` was more consistent with `flowSet`->`fs`, `GatingHierarchy`->`gh`, `GatingSet`->`gs`.

**Comment by mikejiang** [comment]
For those gating function pairs `gate_funcA` and `funcA`, the later was meant to be deprecated in favor of the `gate_` prefixed version. see RGLab/openCyto#69

**Comment by jacobpwagner** [comment]
Yep. Aside from the code itself I actually used that issue and commit as a guide. So does the set of deprecations for those look good or does something look amiss?

**Comment by DillonHammill** [comment]
Just a comment. The noun_verb ROpenSci naming system is extremely useful as autocomplete makes it easy to find functions to accomplish a particular goal 

For example if users want to do something to a gs they start with gs, then the object/item they want to change (e.g. pop) followed by what they want to do (e.g. add or remove).

```{r}
gs_pop_add()
gs_pop_remove()
```
Typing `gs_` will reveal any `gs` associated objects that can be modified and  in what way.

**Comment by jacobpwagner** [comment]
Regarding the `gate_funcA` type functions and their deprecated `funcA` equivalents, should I defunct the `funcA` versions at this point? I can leave them all as just deprecated, but then if a user calls `funcA`, they'll get two layers of deprecation warnings (one from `gate_funcA` and one from `ff_gate_funcA`). 

The same applies to `cytokine`, which was deprecated for `gate_tail`, and `.cytokine`, which was deprecated for `tailgate`, which in turn just calls `gate_tail` without a deprecation warning.

**Comment by mikejiang** [comment]
Personally I prefer to keeping `gate_*` as they are without adding `ff_`.

**Comment by jacobpwagner** [comment]
Yeah, I'm fine without prefixing the `gate_` methods with `ff_`. It probably just unnecessarily adds length. We also then wouldn't need to think about adding `cf_` versions for consistency with the cytoset branch. What do you think about `fs_prior_flowClust`? Just leave it as `prior_flowClust`?
