### ISSUE TITLE
Complete cytoframe/cytoset accessor/mutator overloads 

### ISSUE THREAD

**Issue by jacobpwagner** [RGLab/flowWorkspace#275]

**Comment by jacobpwagner** [comment]
Specifically, I think that we will have to allow for re-sizing of the data matrix at the level of `cytoframe::exprs<-` or `CytoFrameView::set_data()`. But as these are not frequently used APIs, they can be made lower priority.

**Comment by jacobpwagner** [comment]
There are also some issues arising in `write.FCS` due to its use of `description` and `description<-`, for which the `flowFrame` method is still being used for `cytoframe` objects. `keyword` and `keyword<-` have `cytoframe` methods written already, so adding `description` and `description<-` methods should be relatively easy.

**Comment by jacobpwagner** [comment]
Although, to Mike's point, `keyword` and `keyword<-` will likely need some work first.

**Comment by mikejiang** [comment]
Currently the only setter for `keyword` is the s4 replacement method `keyword<-`, which is mainly for editing the `keyword` **value**, e.g. 
```r
keyword(cf)[["Patient ID"]] <- 4
```
To change keyword **name**, it requires some extra efforts
```r
kw <- keyword(cf)
kn <- names(kw)
names(keyword(cf))[match("Patient ID", kn)] <- "patient id"
```
which isn't straightforward for most users. (similarly for deletion).

It will be handy to provide the convenient wrappers for easy deleting/changing `keyword` name. i.e.
```r
cf_rename_keyword(cf, "Patient ID",  "patient id")
cf_remove_keyword(cf, "Patient ID")
```
