### ISSUE TITLE
How can I copy a node, and all of its descendents, to another parent node?

### ISSUE THREAD

**Issue by traumenCapote** [RGLab/flowWorkspace#278]
I know I can move a node with moveNode, but how do I copy/clone a node from one parent node to another? I can clone an entire gating set, but I don't see how to clone a single node.

**Comment by mikejiang** [comment]
You mean copy the gates from the sub-tree (i.e. the node and all its decedent nodes) to another node within the same `gs`?
It's currently not implemented but can be done by traversing that sub-tree and making `addGate` calls along the way. 
@gfinak @jacobpwagner Do you see if there is practical value of this feature?

**Comment by traumenCapote** [comment]
Yes, that what I mean. How else would I measure %positivity of a marker, for which I've measured by defining a gate, for many different cell populations? How would I do that besides copying that node to the many cell populations? 
![rplot](https://user-images.githubusercontent.com/37724550/52815353-7b046e80-306c-11e9-9eb2-8c42d319e7b2.png)

**Comment by gfinak** [comment]
Yes, I think it's worth implementing if it doesn't exist.

**Comment by traumenCapote** [comment]
Thanks for the response. But can you comment further. I am new to using the flowWorkspace package but this seems like something that would be needed very regularly. What do other people do when they need this functionality? Can you provide example code for “traversing that sub-tree and making `addGate` calls along the way”?

**Comment by mikejiang** [comment]
We are working on it and will provide an convenient wrapper for you.

**Comment by traumenCapote** [comment]
> We are working on it and will provide an convenient wrapper for you.

Great, thank you!

**Comment by jacobpwagner** [comment]
@traumenCapote ,  as of 072ddc665463b65dc55a3e7a960c1a2357a2a895 I added `copyNode` to serve this purpose. Please try it out at your convenience and let me know how it goes.

**Comment by jacobpwagner** [comment]
@traumenCapote. I'm closing this issue, assuming `copyNode()` is behaving properly. Feel free to comment here if that's not the case and I will re-open it.
