### ISSUE TITLE
Split parent node of GatingSet into n descendant nodes

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#279]
Hi Mike,

Do you think it would be possible to split a parental node of GatingSet into `n` descendant nodes if you know which cells belong to each node?

For example when the nodes are defined by a multi-dimensional clustering algorithm where we know which events to include in which nodes - but there aren't any gates?

Dillon

**Comment by mikejiang** [comment]
`GatingSet` supports adding clustering results as a factor vector. see https://github.com/RGLab/CytoML/issues/45#issuecomment-416739231

**Comment by DillonHammill** [comment]
Great! Have you tried this approach using an openCyto plugin? Would this be possible or is the lack of gates an issue?
