### ISSUE TITLE
Extracting FCS files from a gating set

### ISSUE THREAD

**Issue by bwin4tang** [RGLab/flowWorkspace#281]
Dear all,

Is there a way to subset a certain gated population into an fcs file as in Subset for a flowSet?

Thank you for your reply.

Best regards,
Mikhael

**Comment by gfinak** [comment]
Yes, call `getData()` on the subset of the GatingSet with the population name you want to extract. This will give you a flowSet that you can write sample by sample to FCS files using `write.FCS` in a loop.
There's no specific API call to do all this since it's pretty trivial.
