### ISSUE TITLE
Normalization Data Seems to be Cloning Instead

### ISSUE THREAD

**Issue by mfahlberg824** [RGLab/flowWorkspace#282]
Hi Greg & Mike,

I'm trying to normalize data and it looks like the function is cloning my data for some reason instead of normalizing it (see code at the end). The "normalized" data looks exactly the same before and after as judged by subsequent density plotting and getData measurements. Additionally - I was wondering why the parseWorkspace function seems to alter the name of the FCS files so that the count is added as a suffix to the file name. Thanks!

Marissa

> xml<-list.files(pattern="wsp",full=T,recursive=TRUE)
> openWorkspace(xml)
FlowJo Workspace Version  20.0 
File location:  . 
File name:  testing.wsp 
Workspace is open. 
Groups in Workspace
         Name Num.Samples
1 All Samples           4
> ws<-openWorkspace(xml)
> gating_set<-parseWorkspace(ws,name=1,isNcdf=FALSE)
Parsing 4 samples
windows version of flowJo workspace recognized.
version X
Creating flowSet...
loading data: ./64324.fcs
Compensating
gating ...
loading data: ./64351.fcs
Compensating
gating ...
loading data: ./64361.fcs
Compensating
gating ...
loading data: ./64362.fcs
Compensating
gating ...
done!
> gating_set
A GatingSet with 4 samples
> getData(gating_set)
A flowSet with 4 experiments.
 column names:
  Time FSC-A FSC-H SSC-A SSC-H Comp-FITC-A FITC-H Comp-PCP-Cy5-5-A Comp-APC-A Comp-AL700-A Comp-APC-H7-A Comp-PacBlue-A Comp-V500-A V500-H Comp-QD655-A Comp-PE-A Comp-PE-CF594-A Comp-PE-Cy7-A
> samplesNames(gating_set)
Error in samplesNames(gating_set) : 
  could not find function "samplesNames"
> sampleNames(gating_set)
[1] "64324.fcs_697268" "64351.fcs_322740"
[3] "64361.fcs_437514" "64362.fcs_454036"
> print(ws)
FlowJo Workspace Version  20.0 
File location:  . 
File name:  testing.wsp 
Workspace is open. 
Groups in Workspace
         Name Num.Samples
1 All Samples           4
> getsamples(ws)
Error in getsamples(ws) : could not find function "getsamples"
> getSamples(ws)
  sampleID      name  count pop.counts
1        1 64324.fcs 697268          2
2        2 64351.fcs 322740          2
3        3 64361.fcs 437514          2
4        4 64362.fcs 454036          2
> GN<-normalize(gating_set,target="64324.fcs_697268")
cloning the gatingSet...
cloning tree structure...
cloning flow data...
GatingSet cloned!

**Comment by mfahlberg824** [comment]
Re-posted with correct styling:

Hi Greg & Mike,

I'm trying to normalize data and it looks like the function is cloning my data for some reason instead of normalizing it (see code at the end). The "normalized" data looks exactly the same before and after as judged by subsequent density plotting and getData measurements. Additionally - I was wondering why the parseWorkspace function seems to alter the name of the FCS files so that the count is added as a suffix to the file name. Thanks!

`> xml<-list.files(pattern="wsp",full=T,recursive=TRUE)
> openWorkspace(xml)
FlowJo Workspace Version  20.0 
File location:  . 
File name:  testing.wsp 
Workspace is open. 

Groups in Workspace
         Name Num.Samples
1 All Samples           4
> ws<-openWorkspace(xml)
> gating_set<-parseWorkspace(ws,name=1,isNcdf=FALSE)
Parsing 4 samples
windows version of flowJo workspace recognized.
version X
Creating flowSet...
loading data: ./64324.fcs
Compensating
gating ...
loading data: ./64351.fcs
Compensating
gating ...
loading data: ./64361.fcs
Compensating
gating ...
loading data: ./64362.fcs
Compensating
gating ...
done!
> gating_set
A GatingSet with 4 samples
> getData(gating_set)
A flowSet with 4 experiments.

  column names:
  Time FSC-A FSC-H SSC-A SSC-H Comp-FITC-A FITC-H Comp-PCP-Cy5-5-A Comp-APC-A Comp-AL700-A Comp-APC-H7-A Comp-PacBlue-A Comp-V500-A V500-H Comp-QD655-A Comp-PE-A Comp-PE-CF594-A Comp-PE-Cy7-A
> samplesNames(gating_set)
Error in samplesNames(gating_set) : 
  could not find function "samplesNames"
> sampleNames(gating_set)
[1] "64324.fcs_697268" "64351.fcs_322740"
[3] "64361.fcs_437514" "64362.fcs_454036"
> print(ws)
FlowJo Workspace Version  20.0 
File location:  . 
File name:  testing.wsp 
Workspace is open. 

Groups in Workspace
         Name Num.Samples
1 All Samples           4
> getsamples(ws)
Error in getsamples(ws) : could not find function "getsamples"
> getSamples(ws)
  sampleID      name  count pop.counts
1        1 64324.fcs 697268          2
2        2 64351.fcs 322740          2
3        3 64361.fcs 437514          2
4        4 64362.fcs 454036          2
> GN<-normalize(gating_set,target="64324.fcs_697268")
cloning the gatingSet...
cloning tree structure...
cloning flow data...
GatingSet cloned!`

**Comment by gfinak** [comment]
The "cloning" refers to the fact that we make a copy of the data that should then be normalized.
I believe you need to specify a target gate and target channels to normalize as well.
The sample names are changed because often the fcs file names are not unique, and can only be uniquely identified by the number of events. I believe it's also possible to turn off this behavior. 
Mike can chime in on that.

**Comment by gfinak** [comment]
Could your paste your sessionInfo() ?
I see you have an error regarding sampleNames() I'm wondering where that comes from.

**Comment by mikejiang** [comment]
To remove `$TOT` from sample names, set `additional.keys = NULL` for `parseWorkspace`.
And here is one example of `normalize` GatingSet http://rpubs.com/wjiang2/465205

**Comment by mfahlberg824** [comment]
Great, it worked! Thank you both so much for the help.

**Comment by mfahlberg824** [comment]
Followed the example closely but it still doesn't seem to be normalizing. In the example you sent, after you run the command the output says:

_cloning the gatingSet...
Normalize CD3
Estimating landmarks for channel CD3 ...
Registering curves for parameter CD3 ...
normalizing sample 1
normalizing sample 2
normalizing sample 3
done!_

However in mine
![post-normalization](https://user-images.githubusercontent.com/49100803/55291654-9c17e900-53a6-11e9-822f-84cea41c83ef.jpeg)
![pre-normalization](https://user-images.githubusercontent.com/49100803/55291655-9cb07f80-53a6-11e9-8598-d2fd9291fe8d.jpeg)

 it only seems to be cloning, even after specifying a target sample, population to normalize, and channel to normalize. Here's my updated code after your comments and the images of the plots before and after normalizing where it doesn't seem to work:

setwd("Desktop/Flow Files")
xml<-list.files(pattern="wsp",full=T,recursive=TRUE)
openWorkspace(xml)
ws<-openWorkspace(xml)
gs<-parseWorkspace(ws,name=1,execute=TRUE,additional.keys=NULL)
_Creating ncdfFlowSet...
All FCS files have the same following channels:
Time
FSC-A
FSC-H
SSC-A
SSC-H
FITC-A
FITC-H
PCP-Cy5-5-A
APC-A
AL700-A
APC-H7-A
PacBlue-A
V500-A
V500-H
QD655-A
PE-A
PE-CF594-A
PE-Cy7-A
done!
loading data: ./64324.fcs
Compensating
gating ...
write 64324.fcs to empty cdf slot...
loading data: ./64351.fcs
Compensating
gating ...
write 64351.fcs to empty cdf slot...
loading data: ./64361.fcs
Compensating
gating ...
write 64361.fcs to empty cdf slot...
loading data: ./64362.fcs
Compensating
gating ...
write 64362.fcs to empty cdf slot...
done!_
pop_to_norm<-"Singlets"
dim<-"Comp-FITC-A"
p1<-autoplot(getData(gs,pop_to_norm),dim) + geom_density_ridges(aes(y=name))+facet_null() + xlim(0,150)
p1
reference_sample<-sampleNames(gs)[1]
gs_norm<-normalize(gs,target=reference_sample,populations=pop_to_norm,dims=dim)
  _cloning the gatingSet...
  cloning tree structure...
  cloning flow data...
  copying data slice:64324.fcs
  write 64324.fcs to empty cdf slot...
  copying data slice:64351.fcs
  write 64351.fcs to empty cdf slot...
  copying data slice:64361.fcs
  write 64361.fcs to empty cdf slot...
  copying data slice:64362.fcs
  write 64362.fcs to empty cdf slot...
  GatingSet cloned!_
p2 <- autoplot(getData(gs_norm, pop_to_norm), dim) + geom_density_ridges(aes(y = name)) + xlim(0,150) + facet_null()
p2

Thanks for the help.
![post-normalization](https://user-images.githubusercontent.com/49100803/55291665-b356d680-53a6-11e9-81fb-3b79a7aaefbb.jpeg)
![pre-normalization](https://user-images.githubusercontent.com/49100803/55291666-b356d680-53a6-11e9-8d77-cb9ff769ce98.jpeg)

**Comment by mikejiang** [comment]
Make sure the `dim` (`Comp-FITC-A`) you are trying to normalize is present in the dimensions that the gate is defined at (I guess `singlet` isn't the right population here)

**Comment by mfahlberg824** [comment]
That's it. Finally got it. Thank you!
