### ISSUE TITLE
parseWorkspace: channel derived with mathematical function in FlowJo causing problem

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [RGLab/flowWorkspace#289]
When trying to parse a workspace, I get the error:

Error in .cpp_parseWorkspace(xmlFileName, sampleIDs, guids, includeGates,  : 
  Derived does not exist in transFlag vector!

"Derived" is an extra channel created by dividing the signal from one channel by another channel within FlowJo using "Derive Parameters" in "Tools". I also changed the scale to log and min = 0.001.

Grateful for any help!

**Comment by gfinak** [comment]
We'd have to play around with derived parameters to get those to work. They're not supported at the moment.  They don't exist in the FCS file, and building support for them is subject to the whims and complexity of how FlowJo decides to support them in the future.

**Comment by PedroMilanezAlmeida** [comment]
Ok, I get that.

I actually don't care about derived parameters for my specific need, but parseWorkspace is throwing an error if the workspace contains a derived parameter.

What if parseWorkspace would give a warning that "Derived Parameters are not supported and could not be included", but would continue parsing for parameters in the FCS file?

**Comment by mikejiang** [comment]
It is expected to behave this way in general according to #262. But your use case could have some specialty that fails the current parser.  We will see if it is reproducible on our end and provide a fix.

**Comment by mikejiang** [comment]
I've pushed the fix to `trunk`. Let me know if it addresses your problem.

**Comment by PedroMilanezAlmeida** [comment]
Cool, thanks. I'll check it out.
