### ISSUE TITLE
Apply Existing GatingHierarchy/GatingSet Gates to New GatingSet

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#293]
Hi @mikejiang and @jacobpwagner,

Just wondering if there is an easy way to copy all the gates from an existing GatingHierarchy/GatingSet to another GatingSet (with different samples)?

Thanks,
Dillon

**Comment by jacobpwagner** [comment]
The easiest way would probably be using `gh_apply_to_new_fcs` on the `FCS` files for the other `GatingSet`. Something like this:
```
library(flowWorkspace)
gs1 <- load_gs(system.file("extdata/gs_manual", package = "flowWorkspaceData"))
fcs2 <- system.file("extdata/CytoTrol_CytoTrol_2.fcs", package = "flowWorkspaceData")
gs2 <- gh_apply_to_new_fcs(gs1[[1]], fcs2)
```
Before the recent API changeover, this was was the `GatingSet` constructor that took an existing `GatingHierarchy` and the vector of FCS filenames.
```
gs2 <- GatingSet(gs1[[1]], fcs2)
```

**Comment by DillonHammill** [comment]
Do think we could supply a flowSet instead of the filenames?

**Comment by gfinak** [comment]
I think the idea behind supplying the filenames is that we can be sure that the data are read, transformed, etc according to the parameters in the original gating set. If we have a flowSet there are no guarantees that the data are on the correct scale, they may already have been manipulated. And then we get people acting confused and filing issues when it doesn't work as expected.

**Comment by DillonHammill** [comment]
Makes sense. So there is no way to transfer gates between GatingSets?

**Comment by gfinak** [comment]
Not at the moment. 
That's a bit the rationale behind having opencyto gating templates.. getting data-driven gates that match a given gating scheme irrespective of the variation from sample to sample.
I don't think we'd rule it out, but it's a significant effort and I'm not convinced of the best way to go about it.

**Comment by DillonHammill** [comment]
That's what I thought too. It would be nice if `gh_generate_template` stored the gates as well for this purpose. Thanks for your help.

**Comment by jacobpwagner** [comment]
Kind of as Greg mentioned, though, including the resultant gate coordinates is kind of not the idea of the `gatingTemplate`. `gh_generate_template` is also just there to build the scaffold of the `gatingTemplate`.

However, you can certainly grab all of the gates from a `GatingHierarchy`:
```
get_all_gates <- function(gh){
  paths <- gh_get_pop_paths(gh)
  paths <- paths[paths != "root"]
  all_gates <- lapply(paths, function(pop_path){
    list("parent"=gh_pop_get_parent(gh, pop_path), "gate"=gh_pop_get_gate(gh, pop_path))
  })
}
```
and apply them to another `GatingSet` (assuming all channels/markers/transformations are in agreement as Greg alluded to):
```
add_all_gates <- function(gs, gate_list){
  for(gate in gate_list){
    gs_pop_add(gs, gate$gate, parent=gate$parent)
  }
}
```
But also as Greg mentioned, that may not be the best idea due to sample variation.

**Comment by DillonHammill** [comment]
Yes! This is exactly what I have chosen to do! Thanks again!

**Comment by jacobpwagner** [comment]
Cool. Yeah, just wanted to highlight that there's nothing really stopping you from doing that. We just don't have a method wrapping that up nicely in part because (again, as the wise Greg mentioned) many users would misuse it and raise issues.
