### ISSUE TITLE
Retain Gate Co-ordinates - Empty Populations

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#298]
Hi @mikejiang and @jacobpwagner,

Just wondering if it is possible to retain the original gate co-ordinates for empty populations?

For example, if we add a rectangleGate to a GatingSet with defined co-ordinatess (e.g. FSC-A = c(0, 50000) and SSC-A = c(0, 50000)), if we try to extract the gate from a empty node (i.e. a sample with no events within this gate) the gate is returned with infinite co-ordinatess (e.g. FSC-A = c(-Inf, Inf) and SSC-A = c(-Inf, Inf)).

Is it possible to retain the original co-ordinates for these nodes so that the gates are consistent across all samples?

Dillon

**Comment by jacobpwagner** [comment]
Can you provide a reprex? This should already be the behavior:
```
> library(flowCore)
> library(flowWorkspace)
> library(ggcyto)	
> data("GvHD")
> 
> gs <- GatingSet(GvHD[1:2])
> empty_gate <- rectangleGate(filterId="emptyGate", list("FL1-H"=c(2500, 5000), "FL2-H"=c(5000, 7500)))
> gs_pop_add(gs, empty_gate, parent= "root")
[1] 2
> extra_gate <- rectangleGate(filterId="extraGate", list("FL3-H"=c(0, 300), "FL2-A"=c(0, 250)))
> gs_pop_add(gs, extra_gate, parent="emptyGate")
[1] 3
> recompute(gs)
done!
> 
> gh_pop_get_gate(gs[[1]], "emptyGate")
Rectangular gate 'emptyGate' with dimensions:
  FL1-H: (2500,5000)
  FL2-H: (5000,7500)
> gh_pop_get_gate(gs[[1]], "extraGate")
Rectangular gate 'extraGate' with dimensions:
  FL3-H: (0,300)
  FL2-A: (0,250)
> gs_pop_get_stats(gs)
   sample                  pop count
1:  s5a01                 root  3420
2:  s5a01           /emptyGate     0
3:  s5a01 /emptyGate/extraGate     0
4:  s5a02                 root  3405
5:  s5a02           /emptyGate     0
6:  s5a02 /emptyGate/extraGate     0
```

**Comment by DillonHammill** [comment]
Do you still have access to the helper-lib file in the CytoExploreR test suite?

If you run lines 1 to 92 and then call:

```{r}
gs_pop_get_gate(gs, "CD69+ CD4 T Cells")
```

Below is a snippet of the output (the last sample does not contain any events within the gate)

$Activation_32.fcs
Rectangular gate 'CD69+ CD4 T Cells' with dimensions:
  Alexa Fluor 647-A: (-0.0402850326476606,4.09207294954423)
  7-AAD-A: (2.59136013434899,4.15547144143088)

$Activation_33.fcs
Rectangular gate 'CD69+ CD4 T Cells' with dimensions:
  Alexa Fluor 647-A: (-Inf,-Inf)
  7-AAD-A: (-Inf,-Inf)

**Comment by jacobpwagner** [comment]
I should still have access I think. I'll look in to it.

**Comment by DillonHammill** [comment]
Thanks, I have pasted the code above...

**Comment by jacobpwagner** [comment]
If you don't `suppressWarnings` , it indicates why:
```
Warning messages:
1: In (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  :
  Activation_33.fcs: Not enough events to proceed the data-driven gating!Returning a dummy gate instead.
2: In (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  :
  Activation_33.fcs: Not enough events to proceed the data-driven gating!Returning a dummy gate instead.
3: In (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  :
  Activation_33.fcs: Not enough events to proceed the data-driven gating!Returning a dummy gate instead.
4: In (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  :
  Activation_33.fcs: Not enough events to proceed the data-driven gating!Returning a dummy gate instead.
```
But I'm hunting down the data-driven gating that is causing it. But anyway, this isn't an issue of adding a rectangle gate, but of default return from a data-driven gating method that is getting no data.

**Comment by DillonHammill** [comment]
Right so the dummy gate is being set by openCyto and then applied to the gatingSet? I was thinking the gate was applied and it was altered within flowWorkspace. Is the a reason for returning these dummy gates?

**Comment by jacobpwagner** [comment]
Well, in the general plugin framework if a data-driven method is to be applied but not supplied with data,  it's sort of impossible/improper to make a restrictive gate. So an infinite-bounded `rectangleGate` just lets everything pass.

**Comment by DillonHammill** [comment]
Ah I get it now, I am using the template to pass manual gates through openCyto which normally generates gates based on the data. In case where there is no data, no gate can be generated so an all-encompassing gate is returned. It is interesting that it does this on a per sample basis when the gate is constructed using the pooled data (i.e. this gatingTemplate entry generates a single gate for all samples using groupBy and CollapseDataForGating, rather than an independent gate for each sample).

**Comment by DillonHammill** [comment]
Hi @jacobpwagner,

Is there any chance that we can bypass the data driven gating if gate co-ordinates have been manually supplied? Happy to more this to openCyto if you like?

Dillon

**Comment by jacobpwagner** [comment]
Hi @DillonHammill. I'm just clarifying the request. You'd like to add a manually-determined gate to a `gatingTemplate` csv file so that it will be added via `gt_gating`? You can accomplish that via `register_plugins` if you register a method that just returns a pre-defined gate, but we could maybe add a "manual" gating_method option as that is admittedly a little cumbersome. 

But is there a reason you need to go through the csv template at all instead of just using `gs_add_gating_method` (for data-driven methods) and/or `gs_pop_add` (for pre-defined gates)? Is this just for the test suite or encapsulated in a method?

**Comment by jacobpwagner** [comment]
Ah, is this about storage of the manual gates defined from `cyto_gate_draw` in a `gatingTemplate`?

**Comment by DillonHammill** [comment]
I have no issue passing gates through the gatingTemplate. The issue is that when openCyto encounters tries to gate an empty population. Instead of applying the supplied gate, it applies a dummy gate because it thinks that we are trying to use a data driven gating method and there is no data.

**Comment by DillonHammill** [comment]
I will try to hunt down where it exists in the code.

**Comment by jacobpwagner** [comment]
Right. Sorry. This is all stemming from this check:

https://github.com/RGLab/openCyto/blob/4bcd0cabcd4698f90278df315ee0d86e2c11a6f6/R/wrapper-functions.R#L46

You can certainly bypass that by tinkering with `openCyto` options to set the `minEvents` below 0 so that check always passes, but that's not advisable as it will then not check before running gating methods that really do need data. We may need to add in support for manually-defined gates that lets them selectively bypass this check.

**Comment by DillonHammill** [comment]
That's it! Can't we just check to see if a gate has been supplied through pp_res?

**Comment by DillonHammill** [comment]
```{r}
if(nrow(fr) <= minEvents & class of pp_res not a gate){
}
```

**Comment by DillonHammill** [comment]
Oh hang on, maybe not... I will have to check what is returned through pp_res.

**Comment by DillonHammill** [comment]
Looks like pp_res only passing the grouping to the gating function, which then selects the gate from a named list.

**Comment by DillonHammill** [comment]
It would be gFunc that contains the gate.

**Comment by DillonHammill** [comment]
Would it not be better to write this check within the gating function itself? That way you can customise the response when no events are present?

**Comment by DillonHammill** [comment]
How about something like this...

```{r}
#' An adapter to connect the gating wrapper function with the \link{gating} method
#'
#' It coerce the input (\code{flowSet}) to a single \code{flowFrame} and apply the gating wrapper function
#' then replicate the gates across samples from the \code{flowSet}.
#'
#' @inheritParams .prior_flowclust
#' @param pp_res preprocessing result produced by the \code{preprocessing} method
#' @param gFunc \code{character} function name of the wrapper function to be invoked
#' @param popAlias \code{character} the population names that are used to determine how many gates to be expected from the gating function
#' @param gFunc_args arguments to be passed to wrapper function('gFunc')
#'
#' @return a \code{list} of \code{filter}s
#' @noRd
.gating_adaptor <- function(fs, pp_res, gFunc, popAlias, channels, gFunc_args) {
  require(openCyto) # since it is going to be invoked by MPI, better load it
  # coercing
  sn <- sampleNames(fs)
  fr <- as(fs, "flowFrame")
  total <- nrow(fr)
  # parse the subSample argument from the gating function argument list
  subSample <- gFunc_args[["subSample"]]
  gFunc_args[["subSample"]] <- NULL # prevent it from passing down to the gFunc
  if (!is.null(subSample)) {
    if (is.numeric(subSample)) {
      if (subSample > 1) {
        samp.ind <- sample.int(total, subSample)
        fr <- fr[samp.ind]
      } else if (subSample > 0) {
        samp.ind <- sample.int(total, subSample * total)
        fr <- fr[samp.ind]
      } else {
        stop("invalid 'subSample' argument: ", subSample)
      }
    } else {
      stop("invalid 'subSample' argument: ", subSample)
    }
  }

  openCyto.options <- getOption("openCyto")
  minEvents <- openCyto.options[["gating"]][["minEvents"]]

  if (is.null(minEvents)) {
    minEvents <- 0
  }

  if (!.isRegistered(gFunc)) {
    stop(sprintf("Can't gate using unregistered method %s", gFunc))
  }
  #      browser()
  thisCall <- substitute(
    f(
      fr = fr,
      pp_res = pp_res,
      channels = channels
    ),
    list(f = as.symbol(gFunc))
  )
  filterRes <- tryCatch(
    {
      do.call(gFunc, c(list(
        fr = fr,
        pp_res = pp_res,
        channels = channels
      ), gFunc_args))
    },
    error = function(e) {
      # Check for sufficient events
      if (nrow(fr) <= minEvents) {
        warning(paste(sn, collapse = ","), ": Not enough events to proceed the data-driven gating!Returning a dummy gate instead.")

        # create dummy rectangleGate
        # TODO: move channels to ... to deprecate x,y channel
        #      dots <- list(...)
        #      channels <- dots$channels
        channels <- as.vector(na.omit(channels))
        nDim <- length(channels)

        if (nDim == 1) {
          gate_coordinates <- list(c(-Inf, -Inf))
        } else if (nDim == 2) {
          gate_coordinates <- list(c(-Inf, -Inf), c(-Inf, -Inf))
        } else {
          stop(nDim, " dimensional gating is not supported yet!")
        }

        names(gate_coordinates) <- channels
        filterRes <- rectangleGate(gate_coordinates)

        # this is flowClust-specific operation, which
        # be abstracted out of this framework

        if (grepl("(flowClust|gate_flowclust)[\\._][12]d", gFunc)) {
          filterRes <- fcRectangleGate(filterRes, priors = list(), posts = list())
        }

        nPop <- length(popAlias)
        filterResType <- ifelse(nPop == 1, "filter", "filters")
        if (filterResType == "filters") {
          filterRes <- filters(lapply(1:nPop, function(i) filterRes))
        }
      } else {
        # Error not caused by event number
        stop(e$message)
      }
    }
  )

  resType <- class(filterRes)
  if (extends(resType, "filter") || extends(resType, "filters") || extends(resType, "logical") || extends(resType, "factor")) {
    # replicate the filter across samples
    list(sapply(sampleNames(fs), function(i) filterRes, simplify = FALSE))
  } else {
    stop("failed at ", paste0(sn), "\n", filterRes)
  }
}
```

Doing it this way means that the event number check is performed only if the gating function errors. If the event number is not responsible for the error, we simply return the error from the gating function for troubleshooting. This should not affect any current behaviours?

**Comment by DillonHammill** [comment]
I can confirm that this code fixes the problem for me. Happy to submit a PR if it passes your checks and you are happy with this approach.

**Comment by jacobpwagner** [comment]
Thanks Dillon. It passes all current tests, but it doesn't look like those really work out the zero-event case anyway. I need to verify that there are no automated methods that will "silently fail" (not produce an error even with zero events). It also may be worth adding a "manual_gate" gating method that allows for specification of a gate object and would bypass the `minEvent` check.

Let me weigh the options and get back to you.

**Comment by DillonHammill** [comment]
Sounds great! Thanks for looking into this.

**Comment by jacobpwagner** [comment]
@DillonHammill , see https://github.com/RGLab/openCyto/commit/c4afb3ad5109d27a382a06d7d3be3e463399c0f3

We still may add direct manual gate specification from the csv templates (interactively it is still easy using `gs_pop_add` instead of `gs_add_gating_method`), but that commit should make it easy to bypass the `minEvents` check on a gate-by-gate basis. Just add `openCyto.minEvents = -1` to your `gating_args` for that whichever rows you would like to bypass the check. That `openCyto.minEvents` arg will be pulled out of the arg list before reaching your function call. I went with `openCyto.minEvents` in case you have `minEvents` in any of your method arg lists.

**Comment by DillonHammill** [comment]
Thanks @jacobpwagner! I will take a look at this later today.

**Comment by DillonHammill** [comment]
Thanks @jacobpwagner this solves the issue on my side!
