### ISSUE TITLE
estimateLogicle question

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/flowWorkspace#299]
Hey guys,

I'm having an issue getting my scaling correct using the estimateLogicle transform. When I plot my data, the populations look like they are scaled appropriately, but the axis labels don't make sense. Here is the code I'm using to get to that point:

#Load files
fcsFiles <- list.files(pattern = "PS1", full = TRUE)
ncfs  <- read.ncdfFlowSet(fcsFiles)
gs <- GatingSet(ncfs)

#Apply Comp
compmatrix <- read.csv("B002_Compensation.csv",check.names=FALSE)
gs <- compensate(gs,compmatrix)

#Apply Tranformation
chnls <- colnames(gs)
fluorchnls <- chnls[7:32]
trans <- estimateLogicle(gs[[1]], channels = fluorchnls, m=5.5)
gs <- transform(gs, trans)

#Apply Gating Template
gt <- gatingTemplate('Gating Template.csv')
gating(gt, gs, mc.cores=4, parallel_type = "multicore")

When I use ggcyto to plot, this is the output:

![Rplot](https://user-images.githubusercontent.com/57542158/73988159-affd7700-48f6-11ea-835f-fd68eface901.png)

Here is the output when I use the logicle scale in FlowJo: 

![image](https://user-images.githubusercontent.com/57542158/73988048-6319a080-48f6-11ea-8929-c5ef5b478d9f.png)

The populations look correct, but the highest data points are being show at 10^3 instead of 10^5.

I also tried using the standard logicle transform like this, but got the same results: 

chnls <- colnames(gs)
fluorchnls <- chnls[7:32]
trans.obj <- logicle_trans(n = 5, equal.space = FALSE, w = 0.5, t = 262144, m = 5.5, a = 0)
transList <- transformerList(fluorchnls, trans.obj)
gs <- transform(gs,transList)

Let me know if you have any thoughts, it would be much appreciated!

**Comment by gfinak** [comment]
That's interesting and it would be good to get a bit more info. Can you pull one of the cells you're interested in and check its time coordinate value, then pull the same cell from the untransformed data, and check its CD3 value, tell us whether it agrees with the flowJo or the ggcyto projection.

**Comment by alexheubeck** [comment]
So I just gated and exported 1 cell from FlowJo and took the MFI in CD3:
FlowJo MFI: 73884
Opencyto Untransformed MFI: 740.08
Opencyto Transformed MFI: 2.95

So it looks like maybe I'm losing two decimal places somewhere, which make sense as far as the transform goes. Any thoughts?

**Comment by gfinak** [comment]
That MFI is pre-comp or post-comp? i.e. is it the MFI immediately after reading in the FCS?

**Comment by alexheubeck** [comment]
I just realized that my comp file had the numbers as full percentages rather than decimals (4 instead of 0.04). That fixed my issue, but I'll have to readjust the gating template. Thanks for helping my realize my mistake!

**Comment by gfinak** [comment]
Super, glad we could help track it down.
