### ISSUE TITLE
Help with Transforms

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/flowWorkspace#300]
Hey guys,

I had an issue with transforms that I was hoping you could give me some advice for. I am attempting to make my opencyto plots match my FlowJo plots, but I can't get the data on the axis below zero to transform appropriately.

Code:

#Load files
fcsFiles <- list.files(pattern = "PS1", full = TRUE)
ncfs <- read.ncdfFlowSet(fcsFiles)
gs <- GatingSet(ncfs)

#Apply Comp
compmatrix <- read.csv("B002_Compensation.csv",check.names=FALSE)
gs <- compensate(gs,compmatrix)

#Apply Tranformation
chnls <- colnames(gs)
fluorchnls <- chnls[7:32]
trans <- estimateLogicle(gs[[1]], channels = fluorchnls)
gs <- transform(gs, trans)

#Apply Gating Template
gt <- gatingTemplate('Gating Template.csv')
gating(gt, gs, mc.cores=4, parallel_type = "multicore")

Here is the current ggcyto plot: 

![T and B Cells](https://user-images.githubusercontent.com/57542158/74052207-5d6f9980-498e-11ea-8c96-d86017eadf48.png)

And this is what I'm trying to match: 

![image](https://user-images.githubusercontent.com/57542158/74052443-b8a18c00-498e-11ea-81f9-bf22bf6e40b1.png)

Any advice would be appreciated, thanks!

**Comment by gfinak** [comment]
What's your ggcyto plot call?

**Comment by alexheubeck** [comment]
Good call, I had the filter=marginalFilter in my ggcyto call, taking it out fixed the issue. Once again, thanks for the help!

**Comment by mikejiang** [comment]
marginalFilter shouldn't truncate the data that much though.

**Comment by alexheubeck** [comment]
This is the call I was using:

TandBCells <- ggcyto(gs[[1]], aes(x = CD19, y = CD3), subset = "Non-Granulocytes", filter = marginalFilter) + geom_hex(bins=300) + ggcyto_par_set(limits = list(x = c(1.2,4.3), y = c(1.2,4.3))) + axis_x_inverse_trans() + axis_y_inverse_trans() + theme_bw()  + facet_null() + scale_fill_gradientn(colours = matlab.like2(300), trans = "sqrt")

Removing the marginal Filter fixed the scaling issue
