### ISSUE TITLE
flowWorkspace Binary on BioC devel

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#306]
@mikejiang, is it possible to have a flowWorkspace binary on BioC devel? Looks like we can only install from source at the moment?

**Comment by mikejiang** [comment]
It is because flowCore failed to compile on bioc with the same error that @hally166 had.
I will track it down and provide the fix.

**Comment by DillonHammill** [comment]
Thanks @mikejiang. Sorry for bothering you so much. I will just need the devel versions until I have patched all the issues causes by the recent API changes. Once this is stable and on BioC release there shouldn't be any issues. It is just in the interim that I need to have users install the devel versions.

**Comment by mikejiang** [comment]
See https://github.com/RGLab/flowCore/issues/175#issuecomment-595868129
I will push to the bioc devel, which should make the binaries available tomorrow for all the related packages.

**Comment by DillonHammill** [comment]
Thanks @mikejiang. Really appreciate it. I will try a fresh install tomorrow.

**Comment by DillonHammill** [comment]
Although the flowWorkspace binary is now available, we still need to compile the flowClust dependency as a binary is not available https://github.com/RGLab/flowClust/issues/20. I haven't had much luck compiling flowClust from source.

**Comment by mikejiang** [comment]
The latest devel version is 3.35.12, which has not been built yet, but should appear later today or tomorrow.
