### ISSUE TITLE
fj_ws_get_keywords call is not imported nor scoped

### ISSUE THREAD

**Issue by kforner** [RGLab/flowWorkspace#307]
Hi,

`.addGatingHierarchies()`  calls ` fj_ws_get_keywords` (line 390) from CytoML.
But CytoML is in Suggests, so that can not work except if CytoML is attached. 

I guess it should be scoped like: `kw <- CytoML::fj_ws_get_keywords(ws, sampleID)` 

My use case is using CytoML without attaching it...

Thanks.

**Comment by mikejiang** [comment]
Done. Thanks!

**Comment by kforner** [comment]
cool!
