### ISSUE TITLE
Is it time for new dev to switch to cytoSet instead of flowSet?

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowWorkspace#318]
Hi,
I guess that you are quite busy, but it would help me to get an answer in order to work on the right foundations. Should new dev be based exclusively on cytoFrame/cytoSet instead of flowFrame/flowSet? The discussion in #294 is interesting but does not bring me a philosophy of dev.
Best,
Samuel

**Comment by gfinak** [comment]
Hi, Sam.
Yes, if you're starting new projects, new packages, now would be the time to embrace the new structures in cytolib. They are what we will be supporting going forward.

**Comment by SamGG** [comment]
Dear Greg,
Thanks for your answer.
