### ISSUE TITLE
problem boolean filter 

### ISSUE THREAD

**Issue by luigidolcetti** [RGLab/flowWorkspace#320]
Hi,

so, on a flowframe I have created some gates to clean up the FACS data and run FLOWSOM pulling out a number of subpopulations, I used the flow som matrix to feed flowworkspace gating set with new populations (everything works fine until this point). Now I am using again boolean filter to merge FLOWSOM population in clusters, but getting the statistics returns only NA. Same happens doing filters on the pre-FLOWSOM gates (even repeating the same OR gate that I used to feed FLOWSOM). Statistics on all the pre-exsisting gates work anyway. The gating set has been saved/loaded via save_gs. Any suggestion where to look for some clues? 

Best regard, Luigi

**Comment by mikejiang** [comment]
Make sure  you run `recompute(gs)` after you add gates/filters to GatingSet.
If it still doesn't work, please paste your example code for troubleshooting

**Comment by luigidolcetti** [comment]
shame on me!
Thank you!

________________________________
