### ISSUE TITLE
gs_pop_get_children throwing error

### ISSUE THREAD

**Issue by luigidolcetti** [RGLab/flowWorkspace#322]
Hi,
I am having some troubles with children and parents retrieval. Let's say I have a tree that looks like this:

/root
/1 /2 /3 ....
/1/Doublets /2/Doublets ... /1/Non-Doublets /2/Non-Doublets ....
/1/Non-Doublets/1 /1/Non-Doublets/2.....
/LIVE /DEAD       (/LIVE by is 1/Non-Doublets/1 | 1/Non-Doublets/5 | ....)
/LIVE/1 /LIVE/2 /LIVE/3 .... 

now, 
gs_pop_get_parent(gatingSet,'/LIVE/1') = /LIVE
gs_pop_get_parent(gatingSet,'/LIVE') = root (... but I suppose this is normal with boolean filter... I mean so far it's the only behavior I noticed although having a trace-back would be useful)

my real troubles start here:

gs_pop_get_children(gatingSet,'/LIVE') =

 Error in .cpp_getChildren(obj@pointer, sampleNames(obj), y, showHidden) : 
  Expecting a single string value: [type=character; extent=2]. 

gs_pop_get_children(gatingSet,'/1') = ... same story

Any idea?

Thank you in advance,
Luigi

**Comment by gfinak** [comment]
I can confirm I can reproduce this error. 
We'll get on a fix asap.

**Comment by jacobpwagner** [comment]
@luigidolcetti , https://github.com/RGLab/flowWorkspace/commit/0217354f1b04aa89dab8845e9f58f98b6508170c should fix it. Thanks for bringing this to our attention and please let us know if you run in to any additional issues.

**Comment by luigidolcetti** [comment]
Perfect! works like a charm!

Thank you very much,
Luigi


________________________________
