### ISSUE TITLE
how to use the open_flowjo_xml

### ISSUE THREAD

**Issue by lifengt** [RGLab/flowWorkspace#325]
I am a new person on R, by reading the example from the ?open_flowjo_xml, I got below message, could you please guide me how to read flowjo workspace?
> try = "single_gating.xml"
> real = open_flowjo_xml(try)
Error in xpathApply(x, "/Workspace", function(x) xmlGetAttr(x, "version"))[[1]] : 
  subscript out of bounds
> file.exists(try)
[1] TRUE
> 
Thanks!
lifeng

**Comment by gfinak** [comment]
What is "single_gating.xml" ? How did you generate it?

**Comment by mikejiang** [comment]
Also, make sure you've updated CytoML to the latest release (v2.0.0). From the error message, looks like it was still using the old code base.

**Comment by lifengt** [comment]
I checked my CytoML, below showed the version: 1.12.1.

Then how should I update the latest version?

Thanks!

Lifeng

> packageDescription("CytoML")
Package: CytoML
Type: Package
Title: A GatingML Interface for Cross Platform Cytometry Data Sharing
Version: 1.12.1
Date: 2016-04-15



________________________________

**Comment by lifengt** [comment]
Thanks for your reply.

I open the flowjo workspace, and click the my single gate, and then go to the power,  click the Show xml for selected nodes.

Then copy all into a word, and save as a work xml file.

Do you think it is right?

lifeng

________________________________

**Comment by mikejiang** [comment]
see https://www.bioconductor.org/packages/release/bioc/html/CytoML.html
for installation instruction. You need latest R release (4.0).

I suspect you might be only saving a portion of your workspace. Try to find `save as` from the menu to export the entire workspace as `wsp` file

**Comment by gfinak** [comment]
No, it's nonsense.
Open the workspace and export the whole thing as XML (for flowJo 9). For flowJo 10, just open the wsp file.

**Comment by lifengt** [comment]
thanks for all your suggestions.

I think I 

> Also, make sure you've updated CytoML to the latest release (v2.0.0). From the error message, looks like it was still using the old code base.

Hi,

**Comment by lifengt** [comment]
> see https://www.bioconductor.org/packages/release/bioc/html/CytoML.html
> for installation instruction. You need latest R release (4.0).
> 
> I suspect you might be only saving a portion of your workspace. Try to find `save as` from the menu to export the entire workspace as `wsp` file

Thanks!

It fixed the problems, I can read the flowjo files in r now.
