### ISSUE TITLE
gatingset_to_flowjo compensation

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/flowWorkspace#328]
Hi there,

I had a question about using gatingset_to_flowjo. When I export my gating set into a FlowJo .wsp, the compensation within the gatingset doesn't go with it. I can apply the compensation in FlowJo separately, but the problem is that the axis names get the "Comp" name added to the parameter. Once the parameter name changes, the gates aren't recognized for that parameter any longer. Is there a way to export the gating set with compensation already applied? 

Thanks!

**Comment by mikejiang** [comment]
Compensation should go to wsp as well. First thing is to make sure you are on the latest BioC release (3.11)

**Comment by alexheubeck** [comment]
Got the latest version working, thanks!
