### ISSUE TITLE
gs_get_singlecell_expression_by_gate error

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#329]
> I’m currently working with flowWorkspace and I’m trying to use gs_get_singlecell_expression_by_gate
> 
> nodes1<- c("mono", "gran", "B", "NK","CD4+", "CD8+", "CD45+")
> gs_get_singlecell_expression_by_gate(gs[1],nodes1)
> 
>  Error in .cpp_getSingleCellExpressionByGate(x@pointer, sample, markers_pops,  : 
>   NA not found! 
> 
> Margaret Cui
> 
>

**Comment by mikejiang** [comment]
It is because `gs_get_singlecell_expression_by_gate` tries to retrieve the markers that are associated with the gates. And `CD45+` gate is defined on `SSC-A`, which doesn't have marker.
```r
gh_pop_get_gate(gs[[1]], "CD45+")
Polygonal gate 'CD45+' with 5 vertices in dimensions Alexa Fluor 405-A and SSC-A
```
This why it reports `NA` error.

**Comment by mlcui** [comment]
Does this mean there is another method to retrieve SSC-A and FSC-A data? It would be useful to help differentiate cell populations with size and granularity on a tSNE plot.

**Comment by gfinak** [comment]
A workaround is to put a `markername` in the `SSC-A` channel.

**Comment by mikejiang** [comment]
We can probably do that automatically within the `gs_get_singlecell_expression_by_gate` call

**Comment by mikejiang** [comment]
Here is the result after the patch,
```r
 testData<-gs_get_singlecell_expression_by_gate(gs[1],nodes1)
.
> head(testData[[1]])
          CD14    CD11b     CD16     CD20 CD4 CD8     CD45     SSC-A
[1,] 0.0000000 0.000000 0.000000 0.000000   0   0 3.984200  12014.69
[2,] 0.0000000 0.000000 0.000000 0.000000   0   0 3.801033  34185.41
[3,] 0.0000000 0.000000 1.039903 2.586087   0   0 3.737607  71270.02
```

**Comment by mlcui** [comment]
Thanks Mike!
