### ISSUE TITLE
Cannot subet cytoset by name

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowWorkspace#343]
@mikejiang & @jacobpwagner, I was hoping that you may be able to help me with a problem that a user is experiencing with their FCS files. The files load in OK, but any operation which calls `fsApply()` internally fails because the individuals flowFrames cannot be extracted by name. I have attached  couple of the file for you try:
[fcs.zip](https://github.com/RGLab/flowWorkspace/files/5144903/fcs.zip)
```{r}
files <- list.files("fcs", full.names = TRUE)
cs <- load_cytoset_from_fcs(files)

# This is the problematic code:
print(sampleNames(cs))
lapply(sampleNames(cs), function(n) {
  print(n)
  y <- cs[[n, returnType = "flowFrame"]]
  print(y)
})
```
Looks like it has something to with the leading underscore in the sample names, when it is removed the code succeeds:
```{r}
sampleNames(cs) <- gsub("^_", "", sampleNames(cs))

# This works:
print(sampleNames(cs))
lapply(sampleNames(cs), function(n) {
  print(n)
  y <- cs[[n, returnType = "flowFrame"]]
  print(y)
})
```

Would be possible to allow leading underscore in sample names to protect the user from encountering this error or perhaps throw a warning when the files are read in? `fsApply()` is used frequently so the code often fails. Sure, the files should not be named this way but it may happen by accident and it is quite difficult to troubleshoot.

Thanks for you help!
Dillon

**Comment by mikejiang** [comment]
let me know if the fix works for you

**Comment by DillonHammill** [comment]
Thanks @mikejiang this is working now.
