### ISSUE TITLE
Out of memory during Parsing the Workspace

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [RGLab/flowWorkspace#345]
Hi and thanks for your help,

During the creation of gatingset I encountered the following error : 
![image](https://user-images.githubusercontent.com/53559811/91832704-055bf580-ec46-11ea-8fa5-1d7d62dc89b0.png)
My group contain 30 CYTOF files (1M of events for each one).

![image](https://user-images.githubusercontent.com/53559811/91833082-84512e00-ec46-11ea-9520-bb17cf232a2f.png)

Any suggestion to solve this issue?

thanks a lot,
Domenico

**Comment by mikejiang** [comment]
This seems to be the same issue that only occurs on 64bit windows. see https://github.com/RGLab/CytoML/issues/111
I am in the process of troubleshooting this. In the meantime, you can launch 32bit version of R to see if it works.

**Comment by mikejiang** [comment]
see the fix here https://github.com/RGLab/CytoML/issues/111#issuecomment-685282760
