### ISSUE TITLE
gs_pop_get_stats MFI returning inf values

### ISSUE THREAD

**Issue by alexheubeck** [RGLab/flowWorkspace#352]
Hi @jacobpwagner,

I updated flowWorkspace to 4.1.13, and the `gs_pop_get_stats` function is now returning `inf` MFI values for all populations that aren't the root node. 

This is the line I'm using: 
`mfi <- as_tibble(gs_pop_get_stats(gs,type = pop.MFI,inverse.trans=TRUE))`

And this is the table it's returning: 

sample | pop | CD3 | CD45 | CD15 | CD45RA | CD14 | CD8 | CD11c | CD25 (IL2Ra) | CD4 | Viability | CD16 | CD123 (IL3Ra) | CD127 (IL7Ra) | IgD | CD304 | CD141 | CD11b | CD19 | CD27 | abTCR | CD34 | CD197 (CCR7) | CD38 | CD56 | HLA-DR
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
B011_PS1_FSQBAZ0BC00-01.fcs | root | 25616.5928 | 291037.172 | 3352.07068 | 27206.7695 | 1312.95978 | 7756.07837 | 1150.63928 | 860.526917 | 3848.13599 | 4028.37671 | 3093.64832 | 1228.84186 | 2012.44177 | 1236.0426 | 1414.28009 | 1399.2337 | 1728.54285 | 524.656433 | 3486.40161 | 38723.1523 | 1229.11938 | 2212.78052 | 5914.71167 | 909.916199 | 2829.16467
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells/Singlets-H | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells/Singlets-H/Singlets-W | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells/Singlets-H/Singlets-W/Cleanup | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells/Singlets-H/Singlets-W/Cleanup/Non-viable | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf
B011_PS1_FSQBAZ0BC00-01.fcs | /Cells/Singlets-H/Singlets-W/Cleanup/Viable | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf | Inf

It's the same thing for the other files in the gating set. I haven't changed anything else in the script since it was working correctly, so just seeing if something changed with that function.

Thanks,

Alex
  

```

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_2.3.2           usethis_1.6.3            gridExtra_2.3            colorRamps_2.3           tidyr_1.1.2              dplyr_1.0.2              tibble_3.0.4             scales_1.1.1            
 [9] cytolib_2.1.20           CytoML_2.1.14            data.table_1.13.2        flowDensity_1.23.0       ggcyto_1.17.0            ggplot2_3.3.2            ncdfFlow_2.35.1          BH_1.72.0-3             
[17] RcppArmadillo_0.10.1.0.0 flowCore_2.1.4           flowWorkspace_4.1.13     openCyto_2.1.2          

```

**Comment by jacobpwagner** [comment]
@alexheubeck , thanks, you caught a pretty nasty bug resulting from some necessary changes for the `flowFrame`->`cytoframe` transition that we hadn't yet made. It's fixed in https://github.com/RGLab/flowWorkspace/commit/c816cf509936a892971004b5f960de2b4650ed59, so hopefully everything should be good after re-installing `flowWorkspace` from GitHub. Otherwise, I'm merging that fix over to Bioconductor so it should be available there in `flowWorkpsace` version `4.1.14` in a couple of days.

**Comment by alexheubeck** [comment]
Thanks @jacobpwagner, much appreciated. I think my scripts are working properly again. Thanks again for the fast response!

**Comment by jacobpwagner** [comment]
Sounds good. I'm going to close this then as this problem seems pretty self-contained and now fixed. But feel free to re-open it if you run in to this again somehow.
