### ISSUE TITLE
Installation Instruction is Outdated

### ISSUE THREAD

**Issue by DarioS** [RGLab/flowWorkspace#379]
`biocLite` is defunct since a couple of years ago. You should advise users to use `install` intead in README.md. There are also typos.
```r
library(BiocInstalller)
bicLite(flowWorkspace)
```
- Three l rather than two in first command's package name.
- o missing in second command's function name.
- [BiocInstaller is defunct](https://www.bioconductor.org/packages//2.11/bioc/html/BiocInstaller.html).

**Comment by mikejiang** [comment]
fixed
