### ISSUE TITLE
Which compensation matrix is used?

### ISSUE THREAD

**Issue by timmocking** [RGLab/flowWorkspace#400]
In the following code snippet:

```r
ws <- open_flowjo_xml(WSP_path)
gs <- flowjo_to_gatingset(ws, name = 1)
gh <- gs[[1]]
mat <- gh_get_compensations(gh)
```

Which compensation matrix should I be getting exactly? The matrix from my FCS $SPILL, or if I have created a new one in FlowJo, that one? Let's say I have one compensation matrix in my FCS file, and multiple ones included in the FlowJo workspace.

**Comment by SamGG** [comment]
While I find your question relevant, I think you will get a quicker answer at doing your own test. Use an empty workspace, drop a FCS file and create a matrix with a distorsion at the intersection of two channels. Let me (and the community) know about the result.

**Comment by timmocking** [comment]
You are completely right. Unfortunately, I do not have access to a FlowJo license/dongle (at the moment).. I can check this next week hopefully but was hoping that there would be some documentation on this somewhere (I can't find it).

**Comment by mikejiang** [comment]
It uses the compensation from flowjo workspace

**Comment by timmocking** [comment]
Thanks a lot!
